/**
 * The AI illustration that accompanies a question's "In practice" scenario.
 *
 * Images live in the PUBLIC `inpractice-illustrations` R2 bucket, served through
 * workers/inpractice-images at /i/<year>-<qindex>.webp with a one-year immutable
 * cache. Public on purpose: they are AI-generated originals from our own scenario
 * text (no PRITE stems, no answers, no copyrighted material), which is what lets
 * this be a plain <img> instead of an authenticated blob fetch.
 *
 * Generated by scripts/illustrations/ -- see that README for the model and the
 * A/B work behind the current settings.
 */
import { useState } from "react";

const BASE =
  (import.meta as any).env?.VITE_ILLUSTRATION_BASE ||
  "https://inpractice-images.correllsoftware.workers.dev";

/** Key format is fixed by the uploader: 4-digit year, 4-digit zero-padded q_index. */
export function illustrationUrl(year?: string, qIndex?: number): string | null {
  if (!year || qIndex == null || !Number.isFinite(qIndex)) return null;
  return `${BASE}/i/${year}-${String(qIndex).padStart(4, "0")}.webp`;
}

export function ScenarioIllustration({
  year,
  qIndex,
  alt,
  onZoom,
  maxWidth = 420,
}: {
  year?: string;
  qIndex?: number;
  alt?: string;
  onZoom?: (src: string) => void;
  maxWidth?: number;
}) {
  // A missing object 404s. Rather than probe first, render optimistically and
  // remove the element on error -- one request either way, no layout flash for
  // the ~100% of questions that do have an illustration.
  const [failed, setFailed] = useState(false);
  const src = illustrationUrl(year, qIndex);
  if (!src || failed) return null;

  return (
    <img
      src={src}
      alt={alt || "Illustration of the clinical scenario described here."}
      loading="lazy"
      decoding="async"
      onError={() => setFailed(true)}
      onClick={onZoom ? () => onZoom(src) : undefined}
      style={{
        display: "block",
        width: "100%",
        maxWidth,
        aspectRatio: "1 / 1",
        objectFit: "cover",
        borderRadius: 12,
        margin: "0 0 14px",
        cursor: onZoom ? "zoom-in" : "default",
        background: "rgba(127,127,127,0.08)",
      }}
    />
  );
}
