"""Open-ended spoken prompts for CPRITE 2023 Q101–200 audio drills."""

PROMPTS: dict[int, str] = {
    101: "What sleep diagnosis best explains a teen who cannot wake for school and sleeps in on weekends?",
    102: "From a sociobiologic and ethnologic perspective, what behavior is most important for the survival of a species?",
    103: "A staff member posts a photo of a patient from a school play with a comment about improvement. What is the psychiatrist's best next step?",
    104: "A physically advanced, high-energy five-year-old is bowling over peers at recess. Mom channels him into soccer and rule-bound physical games. Which Thomas and Chess temperament trait is she responding to?",
    105: "What part of the brain is a site of postnatal central nervous system neurogenesis in humans?",
    106: "A child admitted for worsening falls has trouble rising from a seat, trips, has daily muscle pain, and falling grades. What study best distinguishes this from conversion disorder?",
    107: "What neurobiologic characteristic explains impaired emotional regulation during adolescence?",
    108: "A 12-year-old has two years of new hallucinations, progressive isolation, flat affect, academic decline, and odd laughing, with a negative medical workup. What is the most likely diagnosis?",
    109: "What polysomnogram finding is consistent with narcolepsy?",
    110: "A five-year-old hides under a table in clear view of the door so her uncle won't see her at a surprise party. Which cognitive concept does this illustrate?",
    111: "What is the most common psychiatric comorbidity in children with fetal alcohol spectrum disorder?",
    112: "A 13-year-old with a long psychiatric history is referred to a community-based system of care. What is a Child and Adolescent Service System Program guiding principle?",
    113: "A child with a normal neuro exam has brief episodes of dizziness, vertigo, occipital headache, and hemiparesis that resolve within a day. What disorder best explains this?",
    114: "The power of a statistical test is equivalent to the likelihood of what?",
    115: "An adolescent develops gynecomastia nine months after starting risperidone. The psychiatrist had explained the risk and documented it. Why is the psychiatrist legally protected from a malpractice claim?",
    116: "When paired with a sleep diary, which test is most useful for assessing a child's typical at-home sleep pattern?",
    117: "Which neuropeptide is likely low in a patient with hypersomnolence and REM onset within five minutes of falling asleep?",
    118: "A manic 16-year-old with messianic delusions has stopped eating, heart rate dips below 50, and antipsychotics cause severe dystonia. What is the best treatment now?",
    119: "A 10-year-old has eight months of medically unexplained abdominal pain. He is fit, athletic, and a good kid who never shows stress. What factor most strongly risks this disorder?",
    120: "Velocardiofacial syndrome, repeatedly implicated in early-onset psychosis, is most often the result of what kind of genetic abnormality?",
    121: "A seven-year-old tantrums during math homework, is put in time-out, and never finishes the work. Tantrums then become more frequent. How should that time-out be classified?",
    122: "What is a classic universal intervention that addresses a social determinant of psychiatric illness rather than targeting already-identified children?",
    123: "Where do most Americans get their information on mental health?",
    124: "An adolescent has six months of worsening unexplained abdominal pain despite hospitalizations and negative workups. The family denies other stressors. When and where should psychiatry evaluate?",
    125: "A family therapist cannot reduce conflicts by teaching common ground, then paradoxically tells the family to have at least one argument a day. Which family therapy modality is this?",
    126: "A child with autism, mild intellectual disability, and ADHD, already on risperidone and long-acting methylphenidate, becomes agitated during an ear exam after non-drug strategies fail. What is the next best medication step?",
    127: "An adolescent with OCD who was well on fluvoxamine 200 milligrams daily suddenly relapses. What is the most likely factor behind the relapse?",
    128: "Which cell type provides scaffolding for the migration of neurons during prenatal neurogenesis?",
    129: "A 15-year-old was discharged from a psychiatric practice a year ago to primary care. Which ethical responsibility still persists for the psychiatrist?",
    130: "At the start of a forensic evaluation, what warning should the clinician review with the youth and family?",
    131: "A previously healthy adolescent has fatigue, bilateral leg weakness, and unilateral vision loss. Contrast MRI shows white-matter lesions in the optic tract and periventricular regions. What diagnosis best fits?",
    132: "Adolescents and young adults with autism spectrum disorder differ from typically developing peers in what aspect of gender or sexuality?",
    133: "A psychiatrist volunteers at a free clinic to keep antipsychotics from being prescribed to socioeconomically vulnerable children. Which ethical principle does this most closely reflect?",
    134: "A psychiatrist asks a reflective, open-ended question about a patient's wish to regain healthy weight despite continued diuretic use. Which therapeutic strategy is this?",
    135: "A patient with very-early-onset schizophrenia has waxy flexibility, echopraxia, echolalia, and almost no intake. Benzodiazepines and atypicals failed. What is the next course of action?",
    136: "A 16-year-old is stable on clozapine 200 milligrams. White count is 3100 and ANC is 1300, with no fever. Besides a hematology consult, what is the best action?",
    137: "A 15-year-old develops progressive confusion, memory loss, hallucinations, a seizure, tachycardia, and hypertension; ultrasound shows an ovarian lesion. What diagnosis is most likely?",
    138: "A 13-year-old recently started on aripiprazole is restless, anxious, irritable, and pacing. What is the next best step?",
    139: "A 17-year-old keeps returning to primary care with mild chest pain, constant worry about the next episode, and hours of nightly online searching. What is the most likely diagnosis?",
    140: "According to the acute threat response system theory of impulsive aggression, which brain region modulates the response by analyzing costs and benefits of actions?",
    141: "Which trauma-response intervention is classified as universal prevention for all exposed children?",
    142: "A child with lupus has five days of lethargy and confusion, then stops eating, drinking, talking, and sleeping, holding odd postures all day. Lorazepam improves mentation. What psychiatric comorbidity is this?",
    143: "Which psychological test is often used to assess visuomotor integration in youth?",
    144: "What finding best discriminates a primary psychotic disorder from psychotic-like phenomena secondary to trauma?",
    145: "A four-year-old has brief spells of dizziness, unsteady gait, darting eyes, and loss of balance without loss of consciousness. What other neurological condition is this child most at risk of developing?",
    146: "A Salvadoran-born teen speaks fluent English with American friends but loves serving pupusas and speaking Spanish at mixed family parties. Which acculturation strategy is this?",
    147: "An adolescent with chronic fatigue has sleep attacks at school, sleep paralysis on waking, and hypnopompic perceptual disturbances. After interview, which test is essential in the workup?",
    148: "A grandparent's scolding of a child's loud morning play only makes the play worse. The psychiatrist says praise quiet play and ignore loud play. What function was the scolding serving?",
    149: "Which childhood mental health condition is associated with the greatest risk of developing alcohol use disorder as an adult?",
    150: "According to self-psychology, what is considered typical in children?",
    151: "Which therapeutic modality is based on the premise that the autonomic nervous system can come under voluntary control through operant conditioning?",
    152: "What is the proposed mechanism by which omega-3 fatty acids exert antidepressant activity?",
    153: "An adolescent struggles to start conversations, has poor eye contact, misses social cues, hates unexpected transitions, is rules-focused, prefers to be alone, and lectures on the solar system. What is the most likely diagnosis?",
    154: "A school-age child has seizures, language regression, and hyperactivity. What EEG finding is most likely?",
    155: "Besides gender-affirming psychotherapy and social supports, what is the initial medical intervention for gender dysphoria at Tanner stage two?",
    156: "After an argument a child says, 'Nobody wants to be my friend anymore!' Which cognitive error is this?",
    157: "What is the primary goal of family therapy for oppositional defiant disorder?",
    158: "After starting an antipsychotic, an adolescent cannot stay seated and reports new restlessness. What is first-line treatment?",
    159: "A 30-month-old stacks blocks beside a peer with a toy car, does not share directly, and shows the blocks to the caregiver. What should you tell the caregiver?",
    160: "A medical student presents a depressed adolescent but never asked about mania. Using the One-Minute Preceptor, what should the resident say first?",
    161: "Parents of a 13-year-old with new conduct-disorder behaviors ask if their child is likely to become a lifetime criminal. What is the most accurate statement about the course?",
    162: "Among youth ages five to twelve, what is the most significant influence on emotional development?",
    163: "In a forensic child psychiatric evaluation, as opposed to a clinical one, who is considered the client?",
    164: "Under the HIPAA Privacy Rule, which type of notes is a special category requiring patient consent before release?",
    165: "Statewide Child Psychiatry Access Programs enhance pediatricians' access to child psychiatrists by using which model?",
    166: "A psychiatrist tells a teen with a substance use disorder, 'It is wonderful that you have been sober for six months.' Which core motivational interviewing skill is this?",
    167: "A school hires a psychiatrist as a consultant after a student suicide. What responsibility belongs to the consultant rather than a treating clinician?",
    168: "Gene imprinting refers to a process in which what occurs?",
    169: "An adolescent has no friends, is preoccupied with superpower fantasies, has vague speech and a fearful affect. What additional finding would support schizotypal personality disorder?",
    170: "What soft neurological sign is most commonly observed in children with ADHD?",
    171: "A researcher wants to study clinical outcomes of children with a rare condition over time. Which research design is best suited?",
    172: "What did a 2015 meta-analysis of placebo-controlled trials find about the risk of tics with psychostimulant use?",
    173: "What is the term for a triplet-repeat expansion that increases severity of a disorder over generations?",
    174: "A three-year-old says a child will look for a doll on the shelf after a sibling moved it there unseen. Which cognitive process have most three-year-olds not yet acquired?",
    175: "An eight-year-old has intrusive gory images of family being harmed that pop into their head, plus checking that everyone is safe, after a minor crash a year ago. What condition fits best?",
    176: "What factor is the strongest predictor of suicide and suicide attempts?",
    177: "The Child Guidance Clinic movement initially began to address which problem?",
    178: "Besides guaranteeing a free appropriate public education, what else does IDEA obligate access to?",
    179: "Children with encopresis are most likely to have which comorbid psychiatric disorder?",
    180: "What did the National Longitudinal Survey of Youth report about adult trajectories of heavy adolescent marijuana users who later quit?",
    181: "Which neuropeptide promotes synaptogenesis and reduces apoptosis during toddlerhood?",
    182: "A 17-year-old on a new antipsychotic presents with dehydration, hyperthermia, tachycardia, and rhabdomyolysis. Besides neuroleptic malignant syndrome, which drug of abuse is most likely on the differential?",
    183: "A forensic psychiatrist evaluates a child who reports physical abuse by a school coach; the family is suing the school. What should be the focus of the forensic evaluation?",
    184: "A meta-analysis reports antidepressants are effective in pediatric patients with a number needed to treat of nine. How should that NNT be interpreted?",
    185: "A saliva screen of 200 samples yields 85 true positives, 15 false negatives, 99 true negatives, and one false positive. What is the sensitivity?",
    186: "According to recent meta-analyses, what is the median age range when girls in the United States begin puberty?",
    187: "Which psychosocial factor most positively impacts the mental health of refugee youth?",
    188: "A child with autism, intellectual disability, and chronic health problems is escalating in the emergency department on guanfacine and morning aripiprazole. Verbal interventions failed. Name three next-best de-escalation approaches?",
    189: "An adolescent has a year of affective instability, severe impulsivity, and recurrent self-harm. Name three additional findings that support borderline personality disorder?",
    190: "When treating depression on a medical floor in a patient with liver failure, name three antidepressants safest because of lower hepatotoxicity risk?",
    191: "Name three evidence-based psychotherapeutic strategies useful in treating pediatric obsessive-compulsive disorder?",
    192: "In normal development, name three skills that noticeably emerge between 18 and 36 months and change how the child interacts with others?",
    193: "Name three long-term neurocognitive sequelae most likely to continue or emerge after moderate to severe traumatic brain injury in a child?",
    194: "Parents of a seven-year-old with ADHD who cannot read at grade level want an IEP. Name three components important to get the school to initiate an IEP evaluation for a learning disability?",
    195: "According to the DSM, name three diagnoses that cannot be diagnosed together with disruptive mood dysregulation disorder?",
    196: "Name three findings about the association between increased social media use and worse mental health in transitional-age youth?",
    197: "Name three brain regions that are part of the brain's default mode network?",
    198: "A four-year-old sits up from sleep, yells, looks fearful, and is tachypneic, sweaty, and tachycardic. Name three diagnoses highest on the differential?",
    199: "Name three laboratory findings that might be elevated in patients with anorexia nervosa?",
    200: "Name three Joint Commission requirements after a child is placed in physical restraints?",
}
