"""Open-ended spoken prompts for CPRITE 2023 Q1–100 audio drills."""

PROMPTS: dict[int, str] = {
    1: "At what age does a typically developing infant selectively recognize their own name?",
    2: "Heavy internet pornography use in adolescent males is associated with which sexual dysfunction?",
    3: "What is a major weakness of the molecular cytogenetic approach in linking chromosomal abnormalities with psychiatric illness?",
    4: "Mahler's theories of a child's ability to separate from parents align with what physical development?",
    5: "A six-year-old who witnessed domestic violence has a doll punch the therapist's doll for snacks. Which learning theory does this illustrate?",
    6: "A teen has minutes-long palpitations, dyspnea, nausea, and doom only when around unfamiliar people or presenting, and fears embarrassment. What is the diagnosis?",
    7: "In interpersonal psychotherapy, which domain is a specific area of discussion with adolescents?",
    8: "In contrast to Western cultures, many non-Western societies view suicide as primarily arising from what?",
    9: "A fifteen-year-old with ADHD plus significant irritability and aggression has no other history. What is the most appropriate first-step treatment?",
    10: "In dollhouse play, a four-year-old's doll hits others and says 'you are bad' and 'I hate you.' Which mental-status component does this most indicate?",
    11: "What term describes a disease phenotype that occurs in only some of the individuals carrying the disease-related gene?",
    12: "What is a core developmental concept proposed by Winnicott?",
    13: "A parent asks to correspond via unencrypted email about an adolescent's care. What is the best clinical use of email?",
    14: "Which factor best predicts generalizability of a study?",
    15: "A psychiatrist is subpoenaed to testify in court as a fact witness. What compensation policy applies?",
    16: "Pathology in which brain region is associated with psychosis in people with epilepsy?",
    17: "What term describes a child's ability to hold the image of a comforting caregiver during an aggressive outburst, promoting self-regulation?",
    18: "In the United States, Black youth are more likely than White youth to be diagnosed with a psychotic disorder. What best explains this difference?",
    19: "A child injured the cribriform plate in a crash. Which neurologic exam finding would indicate high-risk cranial nerve injury?",
    20: "An abused child hides in the closet when the garage door opens, even though the abusive parent no longer lives there and hiding never prevented the abuse. Which learning model explains this fear?",
    21: "A child with focal epilepsy is considering surgery after failed medications and a ketogenic diet. The family worries about language loss. Which diagnostic study would address that concern?",
    22: "Which agent most likely lowers serum lithium when taken concomitantly?",
    23: "Which intervention is considered harm reduction related to alcohol use in adolescents?",
    24: "A child with autism screams during homework, and parents immediately give a timeout, which lets the child avoid the work. What intervention best reduces the screaming over time?",
    25: "In the mental status assessment, a unique component of evaluating infants may include observation for what?",
    26: "A young child with PTSD shows poor attachment to parents. Which evidence-based manualized treatment has shown improvement in affect regulation?",
    27: "Which imaging method best assesses neuronal connectivity in children with neurodevelopmental disabilities?",
    28: "What is the most common method of completed suicide in youth ages ten to fourteen?",
    29: "An adolescent has a five-day episode of irritability, all-night organizing, talking out of turn, inattention at school, and more provocative dress, while still attending class. What is the most appropriate diagnosis?",
    30: "Which personality disorder is most frequently comorbid in patients with bulimia nervosa?",
    31: "Which drug is first-line disease-modifying therapy for pediatric multiple sclerosis?",
    32: "A researcher plans to offer one hundred dollars to adolescents who complete a study. What is the most important ethical factor to consider?",
    33: "A medically stable teen with chronic anorexia cannot maintain weight after outpatient failure, with school refusal, academic decline, heart rate of sixty, and no suicidality. What setting is best now?",
    34: "What is AACAP's stance on isolation for more than twenty-four hours as discipline in a youth correctional facility?",
    35: "A seventeen-year-old on risperidone for schizophrenia develops galactorrhea and confirmed hyperprolactinemia; pregnancy test is negative. What is the next best step?",
    36: "Substance-induced psychosis is most strongly associated with later schizophrenia after which substance?",
    37: "Which plasma marker has been found elevated in response to acute stress?",
    38: "A fifteen-year-old starts cognitive behavioral therapy for needle phobia. Which component of therapy is most central?",
    39: "Under the Individuals with Disabilities Education Act, a manifestation determination review must be held when what occurs?",
    40: "Which examination finding supports schizophreniform disorder rather than epileptiform psychosis?",
    41: "Which receptor's expression has most conclusively been shown to be altered by epigenetic modification after childhood sexual abuse?",
    42: "Which characteristic of childhood experience appears to decrease the risk of developing a psychiatric disorder as an adult?",
    43: "In the TEA trial of antipsychotics in youth with psychosis, what best describes the association between weight gain and antipsychotic regimen?",
    44: "A researcher assigns five schools by lottery to a social-emotional intervention and five to control. Which study design is this?",
    45: "Which substance increases appetite when its serum concentration decreases?",
    46: "Functional abdominal pain in childhood is most closely associated with what?",
    47: "In the ABCD study, among students with similar externalizing behaviors, which variable had the greatest adjusted odds of detention or suspension?",
    48: "Which hypothalamic nucleus receives input from the retina and regulates diurnal rhythms?",
    49: "Which brain region is implicated in selectively processing faces and thought to be involved in the neuropathology of autism?",
    50: "Which factor mediates the influence of both socioeconomic status and neighborhood effects on adolescent conduct disorders?",
    51: "A child has daytime sleepiness and hallucinations upon awakening. Polysomnography shows decreased REM latency. What next test best confirms the diagnosis?",
    52: "A nine-year-old with oppositional defiant disorder refuses a parenting-intervention study, but the parent consents. What is the most appropriate next step?",
    53: "A school-age child spends four hours a day arranging a room and is highly distressed if items look off. Exposure and response prevention plus max-tolerated fluoxetine gave partial benefit. Which medication is evidence-based augmentation?",
    54: "In psychiatric billing, what do current procedural terminology codes refer to?",
    55: "A well-functioning fourteen-year-old describes frequently switching sexual-orientation labels and career plans, without gender distress. How should the psychiatrist understand this?",
    56: "In children with juvenile myoclonic epilepsy, which antiepileptic can exacerbate myoclonus?",
    57: "A ten-month-old crawls toward a visual cliff. The study tests whether the caregiver's facial expression changes whether the infant crosses. Which developmental task is being assessed?",
    58: "What is the most common cause of inappropriate disclosure of psychiatric information through security breaches?",
    59: "An emergency physician evaluates a child with new obsessions and cannot determine a cause. Which step is considered lifelong learning?",
    60: "A school-age child has labile affect incongruent with speech, explosive variable speech rhythm, a brisk gag with intense crying, and new dysphagia with a normal oropharynx. What neurologic syndrome best explains this?",
    61: "Which self-report scale should a psychiatrist give an eight-year-old with depression to augment clinical assessment?",
    62: "The capacity for shame typically develops by what age?",
    63: "A clinic flags charts if body mass index rose more than two points after an antipsychotic. This system is an example of what?",
    64: "An overweight ten-year-old has Tanner stage two breasts and pubic hair, normal development, and no medical history. The parent fears she is too young for puberty. What most likely explains these findings?",
    65: "A psychiatric assessment to determine transplant eligibility presents a dilemma for the evaluator under what ethical principle?",
    66: "Which substance decreases hippocampal neurogenesis?",
    67: "A thirteen-year-old with severe weight loss and restrictive eating leaves the table quickly and spends long periods in the bathroom, denying problem behaviors. Which lab is most helpful to check the report?",
    68: "An eight-year-old in foster care after physical abuse says nobody loves him, might walk into traffic, feels sad, and hears voices calling him no good, but is doing well at school. What diagnosis is high on the differential?",
    69: "An adolescent has escalating in-game spending sprees, weeks of dysphoria when the game is uninstalled, lying, and stealing for in-game money. Before considering an addictive disorder, what must be ruled out?",
    70: "Which receptor primarily regulates arousal and the sleep-wake cycle?",
    71: "When an adolescent returns from a juvenile facility to public school, what does the Juvenile Justice and Delinquency Prevention Act mandate the school must do?",
    72: "Which characteristic is commonly demonstrated in youth who have experienced frequent foster care placements?",
    73: "Reciprocal inhibition between the medial prefrontal cortex and which brain structure decreases the stress response?",
    74: "A transcranial magnetic stimulation versus sham trial compares mean Hamilton depression scores at two weeks in two adolescent groups. Which statistical test is most appropriate for detecting group differences?",
    75: "Compared with a six-year-old, a twelve-year-old dying of cancer is more likely to express grief about losing what?",
    76: "What is the most widely reported and replicated brain-growth phenotype during the first year of life in autism spectrum disorder?",
    77: "An eight-year-old of separated parents draws herself, father, and brother under a tree outside the home. What is the most appropriate comment?",
    78: "A ten-year-old with a bipolar family history has not slept for five days, believes he is a superhero, and tried to jump from a third-story window. Which medication has the best evidence for these acute pediatric symptoms?",
    79: "What is the legal basis for a private school to refuse to honor a student's 504 plan?",
    80: "In equivocal sleep studies, cerebrospinal fluid orexin below one hundred ten picograms per milliliter is most suggestive of which sleep disorder?",
    81: "Beginning as early as seven to nine months, development of which motor skill is critical in establishing social preferences?",
    82: "Increased pruning and myelination between ages thirteen and twenty-five most improves which ability?",
    83: "A psychiatrist encourages talking, listens actively, gives accurate empathy, and does not aim to uncover repressed material. Which therapy is this?",
    84: "How are premenstrual affective symptoms related to gonadal hormone levels?",
    85: "A sixteen-year-old on lithium presents with confusion, nausea, vomiting, diarrhea, and a lithium level of two point five after an upper respiratory illness treated with over-the-counter cold medicine. Which common ingredient most likely contributed?",
    86: "Which technique in a child diagnostic interview is projective?",
    87: "Secretion of prolactin is under direct regulation of what class of neurons in the tuberoinfundibular hypothalamus?",
    88: "Which legislation addresses differential management and reimbursement of mental illness by insurance companies?",
    89: "Over three days a twelve-year-old is mute and unresponsive to voice, touch, or pain, with a fixed gaze, odd posture, and rigidity, but is afebrile with normal vitals. Besides supportive care, what is the next best step?",
    90: "An adolescent has recurrent acute lymphoblastic leukemia; the team is concerned but has not yet determined whether the illness is life-limiting. What is the most appropriate next step in advance-care-planning counseling?",
    91: "Which rating scale provides a general primary-care screening of behavioral-health symptoms that identifies risk for childhood psychiatric disorders?",
    92: "After missing a soccer goal, a young child says they don't want to play because they're not as good as the other kids. Which Erikson stage does this illustrate?",
    93: "A guarded seventeen-year-old proudly says they have been drug-free for two months and are in a substance-use program. What initial response is most likely to facilitate engagement?",
    94: "An adolescent receiving interpersonal psychotherapy for depression is in the initial phase. Which task is the adolescent most likely doing in these early sessions?",
    95: "An adolescent assaults a pharmacist to steal drugs they then sell for profit. What type of aggression is this?",
    96: "A seventeen-year-old discloses six months of recurrent, sexually arousing, shame-inducing fantasies about a ten-year-old neighbor. What is the most likely diagnosis?",
    97: "A four-study forest plot of Drug X for adolescent anxiety is shown. What conclusion can be drawn?",
    98: "A study reports a five-fold increased risk of a rare side effect after childhood medication exposure versus unexposed. What distinction is most important to communicate when interpreting this?",
    99: "A five-year-old snores, coughs, and grinds teeth at night, has low playground energy, and gets cranky in the early afternoon. Which test is most useful to determine the etiology?",
    100: "A postpartum teen has partial mood improvement after twelve weeks of fluoxetine forty milligrams plus CBT. She has intrusive thoughts of throwing the baby out a window and avoids windows, without psychosis or suicidality. What is the next pharmacologic step?",
}
