"""Topics and explanations for CPRITE 2024 Q101–200.

Explanations follow the keyed (green-shaded) answers in the source quiz.
"""

META: dict[int, tuple[str, str]] = {
    101: ("Research Methods",
         "Crossover designs reuse each subject as their own control, so fewer participants are needed for the same power. They do not automatically reduce selection bias, are often harder to blind (period/order effects), and limit generalizability when washout is incomplete or the condition is unstable. Synergy is a factorial, not a crossover, question. Teaching point: Crossover = same people, both conditions → smaller N."),
    102: ("Psychotherapy",
         "Letting the anxious teen talk about tomorrow's meet instead of interpreting the forgotten invitation is supportive: the therapist follows the patient's current distress and ego need. IPT would target the mother–daughter role dispute. CBT would test the performance thought. DBT would add skills. Psychodynamic work would interpret the omission. Teaching point: Follow today's affect rather than the avoided conflict = supportive psychotherapy."),
    103: ("Neuroscience",
         "The most replicated early MRI finding in autism is brain overgrowth by the end of the first year (accelerated volume increase after a normal or slightly smaller birth size), not a larger brain at birth. Hippocampal atrophy, limbic neuronal dropout, and septum–mammillary disconnection are not the classic infant ASD signature. Teaching point: ASD brains grow too fast in year one."),
    104: ("Neuroscience",
         "Lateral-hypothalamic orexin/hypocretin neurons project to LC, raphe, and LDT/PPT to stabilize wakefulness; their loss is narcolepsy type 1. Food craving, motor control, stress, and thermoregulation involve other hypothalamic circuits. Teaching point: Orexin to arousal nuclei = stay awake."),
    105: ("Development",
         "Toddler language accelerates when caregivers use more explanatory talk (why/how the world works), not babble, commands, directions, or limit-setting. Quantity of child-directed speech matters, but the boards key quality: explanation. Teaching point: Explain more; toddlers talk sooner."),
    106: ("Psychopharmacology",
         "ADHD plus ODD with explosive tantrums still starts with a stimulant — treating ADHD often drops the oppositionality. Antipsychotics, benzos, GABA agonists, and SSRIs are not first-line for this combination. Teaching point: ADHD+ODD first-line = stimulant, not an antipsychotic."),
    107: ("Psychotherapy",
         "'You cannot imagine feeling good without smoking weed' is a complex reflection that restates the patient's own logic and invites more talk — classic MI. Lectures, judgment, side-effect checklists, and 'can I share the hazards' are the righting reflex. Teaching point: MI next line = reflect the patient's reason, don't educate."),
    108: ("Neuroscience",
         "Functional hypothalamic amenorrhea is CRH/stress-axis overdrive suppressing hypothalamic GnRH, so LH/FSH and estrogen fall — not rise. HPA activity is increased, not decreased. Teaching point: Stress amenorrhea = GnRH turned down."),
    109: ("Psychopathology",
         "This is delayed sleep-phase: sleep is consolidated but clocked 6 AM–3 PM. Chronotherapy delays bedtime further around the clock until it lands on a school schedule. An earlier bedtime fails (they cannot fall asleep). Melatonin can adjunct later; PSG is for apnea/PLMD; watchful waiting will not reset before school. Teaching point: Delayed sleep-phase reset = chronotherapy (delay around the clock)."),
    110: ("Development",
         "Early verbal-language deficits are the neurocognitive factor most tied to later aggression (limited words → limited delay and negotiation). Attention, processing speed, STM, and visuospatial skill are weaker predictors. Teaching point: Poor early language → later aggression."),
    111: ("Research Methods",
         "NNT is an effect-size (clinical magnitude) statistic. P values are significance, not size. Means/SD describe the sample; CIs are precision around an estimate. Teaching point: NNT answers 'how big is the benefit?' not 'is it significant?'"),
    112: ("Psychopathology",
         "Picking and plucking driven by a conviction that the unremarkable face is deformed is body dysmorphic disorder (appearance belief), not primary excoriation or trichotillomania (those lack the dysmorphic idea). Insight is too good for somatic delusional disorder; OCD would have broader obsessions/compulsions. Teaching point: Skin picking to fix a 'deformed' normal face = BDD."),
    113: ("Ethics & Forensics",
         "Promoting awareness of children's mental-health needs, without asking for a specific bill or vote, is advocacy, not lobbying. PAC donation and training requirements do not by themselves make capitol education appropriate; lobbyist registration is for lobbying. Teaching point: Education/awareness = advocacy; a specific bill = lobbying."),
    114: ("Research Methods",
         "ARR = 0.50 − 0.25 = 0.25; NNT = 1/ARR = 4. Teaching point: NNT = 1 / (control event rate − treatment event rate)."),
    115: ("Neuroscience",
         "Childhood-trauma × FKBP5 A/T risk alleles disrupt glucocorticoid-receptor feedback, producing cortisol-feedback resistance (the receptor no longer shuts the HPA axis off cleanly). It is not simply more cytoplasmic GRs, chromatin repression as the main story, adrenal overstimulation, or HPA shutdown. Teaching point: FKBP5 trauma risk = broken cortisol negative feedback."),
    116: ("Development",
         "A cognitively intact 12th-grader who understands death and wants a last trip is using normal adolescent future-orientation and meaning-making, not adjustment disorder, delirium, amnesia, or preschool-level death concepts. Teaching point: A last big plan after terminal news can be developmentally normal."),
    117: ("Psychopathology",
         "Chronic NSSI is among the strongest predictors of later suicide attempts, outranking nonspecific depression, impulsivity, worry, or conflict when those are compared head-to-head in many youth samples. Teaching point: Repeated self-injury is a suicide-risk marker, not 'just a coping skill.'"),
    118: ("Psychopharmacology",
         "Waxy flexibility, mutism, and staring in anti-NMDA encephalitis is catatonia; first-line symptomatic treatment is a benzodiazepine (lorazepam) while immunotherapy continues. Antipsychotics can worsen catatonia/NMS-like pictures. Clonidine and bromocriptine are not the catatonia rescue. Teaching point: Autoimmune catatonia → lorazepam, not a neuroleptic."),
    119: ("Neuroscience",
         "Fatigable afternoon diplopia and ptosis is myasthenia gravis. MG associates with thymic hyperplasia or thymoma. Thyroid, pituitary, pancreas, and adrenal are not the classic pairing. Teaching point: Fatigable ptosis/diplopia → think thymus."),
    120: ("Development",
         "A 41-month-old with ~20 total words and only a few two-word phrases is language-delayed even allowing for bilingualism (combined vocabulary should be much larger by 3). Refer to SLP; do not 'wait because bilingual,' force one language, or use the child as interpreter. Teaching point: Bilingualism does not excuse a tiny total vocabulary at 3."),
    121: ("Systems & Prevention",
         "Routine PHQ-9 before depression visits is measurement-based care; the outcome most consistently tied to it in practice-change literature is a better patient experience (feeling tracked, involved). It does not reliably cut polypharmacy, comorbidities, visit number, or access by itself. Teaching point: MBC's most immediate win is the patient's experience of being measured and followed."),
    122: ("Psychopharmacology",
         "SSRIs treat PMDD in days, not the weeks needed for MDD, which is why luteal-phase-only dosing works. Comorbid anxiety, withdrawal, cycle irregularity, and cost do not justify intermittent dosing. Teaching point: PMDD SSRI response is fast → luteal dosing is enough."),
    123: ("Assessment",
         "ADOS (with ADI-R) is the gold-standard observational instrument for ASD. ABC, CARS, SCQ, and M-CHAT are screens or severity scales, not the diagnostic gold standard. Teaching point: ASD gold-standard test = ADOS."),
    124: ("Psychotherapy",
         "Using substances to take away distress is negative reinforcement (remove aversive state → use increases). Cue craving is classical conditioning; anticipating calm is expectancy; being around drugs is stimulus control; needing more is tolerance. Teaching point: Use to relieve a bad feeling = negative reinforcement."),
    125: ("Psychopathology",
         "The face is the most common excoriation site (then arms/hands). Legs, scalp, and isolated fingers are less typical as the primary site. Teaching point: Skin-picking disorder loves the face."),
    126: ("Neuroscience",
         "New mood change, paresthesia, and visual change in a teen is demyelination until proven otherwise; FLAIR is the sequence that shows MS plaques best (CSF-suppressed T2). T1, GRE, DWI, and SWI answer other questions (anatomy, blood, stroke, iron). Teaching point: Suspected MS → FLAIR."),
    127: ("Development",
         "Adolescents often prefer peers over parents when talking about a death. Death-play and 'is Grandma still eating?' are young-child responses; self-focus is more preschool/early school-age; reunion fantasy is also younger. Teaching point: Teen grief → they talk to friends first."),
    128: ("Development",
         "A 3-year-old who needs a bedtime routine, fears the dark, and is flexible everywhere else is typical preschool. ASD needs broader rigidity/repetitive behavior. SAD would show daytime separation trouble. GAD is impairing worry. PTSD needs trauma. Teaching point: Bedtime ritual + dark fear at 3 = normal."),
    129: ("Psychotherapy",
         "Among listed psychotherapies, AACAP parameters give interpersonal therapy the strongest evidence base for adolescent MDD (CBT is also well supported but parent-involved CBT, PCIT, ABFT, and brief psychoanalytic therapy are not the keyed first pick here). Teaching point: Adolescent MDD psychotherapy with the most cited evidence = IPT."),
    130: ("Neuroscience",
         "Caspi: 5-HTTLPR short/short plus negative life events raised adult depression risk (gene × environment). Treatment access, comorbid anxiety, parental depression, and prepubertal onset were not the interaction in that landmark paper. Teaching point: Short serotonin-transporter allele hurts when life events pile on."),
    131: ("Assessment",
         "PSG is required to diagnose periodic limb movement disorder (you have to see the movements and arousals). Sleepwalking, enuresis, and bruxism are clinical. Epilepsy needs EEG. Teaching point: PLMD diagnosis = overnight PSG."),
    132: ("Psychopharmacology",
         "Clomipramine's edge in OCD is more potent serotonin-reuptake inhibition than other TCAs (it is the most serotonergic TCA). It is not a 5-HT agonist/antagonist, not a NE-selective story, and not about adrenergic blockade. Teaching point: Clomipramine for OCD = strongest TCA SRI."),
    133: ("Neuroscience",
         "HIV child, cognitive decline, new seizures, EBV in CSF = primary CNS lymphoma (EBV-driven in AIDS). Progressive HIV encephalopathy and ADC do not show EBV. CMV and toxo are opportunistic but not this PCR signature. Teaching point: HIV + EBV PCR in CSF + mass/seizures = PCNSL."),
    134: ("Development",
         "Lifelong tracking below the 5th percentile, delayed bone age, and Tanner 2 at 15 with normal GH/thyroid is constitutional growth delay. Familial short stature has normal bone age. Stimulant effect would deflect after last year's start, not a whole-childhood curve. Malnutrition and hypopituitarism are ruled out by labs/weight tracking in parallel. Teaching point: Short + delayed bone age + late puberty = constitutional delay, not the methylphenidate."),
    135: ("Development",
         "Perceptual narrowing of phonemes (all languages at 3 months → native only by 12) is synaptic pruning of unused auditory contrasts. Synaptogenesis/overproduction and arborization are growth, not the loss of unused distinctions. Teaching point: Losing non-native sounds = pruning."),
    136: ("Systems & Prevention",
         "Relapse prevention is tertiary (the illness already exists; you prevent recurrence). Primary/universal/selective happen before disease; secondary is early detection. Teaching point: Relapse prevention = tertiary prevention."),
    137: ("Psychopathology",
         "DSM-5 gender dysphoria in children requires a strong desire to be the other gender (not just expression, anatomy dislike, pubertal anxiety, or parent report). Teaching point: Child GD criterion that must be there = desire to be the other gender."),
    138: ("Systems & Prevention",
         "Anthropology's look at policies that shape resources and constraints is a structural perspective (structural competence / structural violence), not merely 'culture,' disparities, SDH, or economics as isolated ideas. Teaching point: Policies that box families in = structure."),
    139: ("Ethics & Forensics",
         "Unsecured texting is acceptable only for non-clinical logistics (appointment times). Diagnosis, updates, side effects, and dosing belong in a secure record/portal. Teaching point: Text for scheduling, not for clinical content."),
    140: ("Systems & Prevention",
         "Replacing expulsion with a support group that keeps the student in school is harm reduction (reduce harm of use/policy, not require abstinence first). Rehabilitation, self-help, case management, and relapse prevention are different frames. Teaching point: Stay in school + support instead of expel = harm reduction."),
    141: ("Assessment",
         "A finger moving toward the nose tests accommodation (near triad: convergence, accommodation, miosis). Ptosis, nystagmus, abduction, and swinging-flashlight RAPD are other maneuvers. Teaching point: Finger to nose for pupils/eyes = accommodation."),
    142: ("Ethics & Forensics",
         "Failure to report suspected child abuse is negligence (a negligent tort). Sexual exploitation, defamation, fraudulent commitment, and intentional infliction of emotional distress are intentional torts. Teaching point: Missed mandated report = negligence, not an intentional tort."),
    143: ("Assessment",
         "Weber (vibrating fork midline on the forehead) tests CN VIII (lateralization). Palate 'ka' is IX/X, head-turn resistance is XI, flashlight is II/III, Romberg is proprioception more than VIII. Teaching point: Midline tuning fork = CN VIII."),
    144: ("Ethics & Forensics",
         "Malpractice elements: duty, dereliction (negligence), direct causation, damages (harm). Intention is for intentional torts; maleficence/preponderance/standardization are not the fourth element. Teaching point: 4 Ds — duty, dereliction, direct cause, damages."),
    145: ("Psychopathology",
         "The most robust environmental predictor of young-child externalizing is directly experiencing violence. Peer aggression, hearing about violence, community rates, and media are weaker. Teaching point: Lived-through violence predicts acting-out more than seeing it on the news."),
    146: ("Development",
         "Checking mother's face before touching the sand and proceeding after a smile is social referencing. Joint attention is sharing focus on an object; hatching/mirroring/social smile are earlier or different. Teaching point: Look-to-caregiver-then-act = social referencing."),
    147: ("Assessment",
         "Normalization names the symptom as something some kids have, then asks — here, suicide. The other lines are symptom/course/impairment questions without that frame. Teaching point: 'Some kids think about suicide. Have you?' = normalization."),
    148: ("Research Methods",
         "'Four times more likely' is relative risk (risk ratio). Absolute risk is the raw difference; confounding, moderation, and attributable fraction are other concepts. Teaching point: 'X times as likely' = relative risk."),
    149: ("Neuroscience",
         "ADHD + optic glioma + café-au-lait + axillary freckling = NF1. Williams, Fragile X, McCune–Albright, and TSC have other skin/neuro signatures. Teaching point: Optic glioma + café-au-lait = NF1."),
    150: ("Psychopathology",
         "Clinician reluctance to diagnose adolescent BPD is driven mainly by stigma (and myth that you cannot diagnose before 18). DSM-5 allows the diagnosis in youth; treatments (DBT) exist; stability is imperfect but not the main barrier. Teaching point: We underdiagnose teen BPD because of stigma, not because of the age-18 rule."),
    151: ("Neuroscience",
         "Two cell lines in one person = mosaicism. Anticipation is expanding repeats across generations; premutation is an intermediate repeat; polymorphism is a common variant; CNV is extra/missing copy number. Teaching point: Two genotypes, one body = mosaic."),
    152: ("Neuroscience",
         "Inattention plus 3-Hz spike-and-wave is childhood absence epilepsy, typically autosomal dominant (complex, but that is the inheritance the boards want). Teaching point: 3-Hz absence → autosomal dominant."),
    153: ("Systems & Prevention",
         "A common telepsychiatry barrier is infrastructure/overhead that payers do not cover. Families often like it; guidelines exist; Ryan Haight is controlled-substance-specific, not all telepsych; there is no national license. Teaching point: Telepsych's usual blocker is unpaid tech/overhead."),
    154: ("Consultation & Schools",
         "Medically stable, waiting for a psych bed: C/L's first job is a safety plan the pediatric team can run tonight — not transferring faster, a big meeting, handing out phone numbers, or jumping to meds for agitation. Teaching point: Boarding on peds → write the safety plan."),
    155: ("Neuroscience",
         "Puberty starts when hypothalamic GnRH becomes pulsatile again, then LH/FSH, then sex steroids. Estrogen/LH/FSH/TSH are downstream or the wrong axis. Teaching point: Puberty restart switch = pulsatile GnRH."),
    156: ("Research Methods",
         "Twin studies (MZ vs DZ concordance) separate genetic from shared-environment contribution. Karyotype, linkage, candidate genes, and NGS find variants, not the heritability split. Teaching point: Genes vs environment pie chart → twins."),
    157: ("Development",
         "Using a stored representation of an old event to make sense of a new one is symbolic/preoperational, arriving in the preschool years. Toddlers have emerging representation; school-age kids already have it. Teaching point: Preschoolers can use a mental picture of last time to understand this time."),
    158: ("Systems & Prevention",
         "'The evil eye did this' is a causal attribution (what the family thinks caused the psychosis). Contextual frame, process explanation, cultural transference, and sociocultural contingencies are other cultural-psych terms. Teaching point: 'What caused it?' answer = causal attribution."),
    159: ("Development",
         "Piagetian reversibility (operations can be undone) is the hallmark of concrete operations. Sensorimotor is action; preoperational is irreversible/egocentric; formal is abstract/hypothetical. Teaching point: Reversibility = concrete operational."),
    160: ("Ethics & Forensics",
         "Treater vs forensic evaluator is dual agency; mixing them undermines the therapeutic alliance (and forensic objectivity). Time, 'too much weight,' extra training, and legality of meds are not the core reason. Teaching point: Don't be both therapist and court evaluator."),
    161: ("Assessment",
         "New agitation, vocalizing, and head-banging in ID/ASD is pain until proven otherwise — dental (and ENT/constipation) before clonidine, aripiprazole, lead, or genetics. Teaching point: New SIB in nonverbal kids → look in the mouth."),
    162: ("Systems & Prevention",
         "Community-based child mental health prioritizes families as partners in planning. Escalating for nonadherence, meds-only, visit caps, and forcing TAY to self-navigate violate that model. Teaching point: Community systems = families at the planning table."),
    163: ("Ethics & Forensics",
         "Mandated reporting is triggered by reasonable suspicion, not physical findings, clear-and-convincing proof, preponderance, or medical certainty. Teaching point: You report on suspicion, not on a courtroom standard."),
    164: ("Psychotherapy",
         "Apologizing for being late and naming the patient's likely feeling models the communication skill the child is learning. Education, suggestion, clarification, and interpretation are other techniques. Teaching point: Do in the room what you want them to do at home = modeling."),
    165: ("Research Methods",
         "Case–control of past maternal caffeine vs later ADHD is classic recall bias (mothers of cases remember exposures differently). Attrition is loss to follow-up in cohorts; selection/publication/channeling are other biases. Teaching point: Retrospective exposure in mothers of cases = recall bias."),
    166: ("Systems & Prevention",
         "Trauma-informed care starts with every employee recognizing trauma signs — not making everyone a TF-CBT therapist, legal definitions, erasing the word, or never asking. Teaching point: TIC step one = all staff can see trauma."),
    167: ("Neuroscience",
         "Depressed adolescents' PSG shows more total REM (and shorter REM latency, more fragmentation, less slow-wave sleep). Increased REM latency, faster sleep onset, less fragmentation, and more SWS are the opposite. Teaching point: Depression sleep = extra REM, not extra deep sleep."),
    168: ("Neuroscience",
         "Lasting psychological sequelae after pediatric TBI track injury severity; anterograde amnesia >7 days is a severity marker. Brief LOC, immediate irritability, and retrograde gaps for the event are weaker. Teaching point: PTA longer than a week predicts lasting problems."),
    169: ("Neuroscience",
         "Lipophilic hormones (steroids, thyroid) cross the membrane, bind intracellular receptors, and run a transcriptional cascade. Surface receptors/second messengers are peptide hormones. They do not bind mtDNA or a single promoter as the whole story. Teaching point: Fat-soluble hormone → intracellular receptor."),
    170: ("Neuroscience",
         "Juvenile myoclonic epilepsy typically needs lifelong treatment. Rolandic and many occipital/absence epilepsies often remit in adolescence. Teaching point: JME / myoclonic = don't stop the meds at 16."),
    171: ("Ethics & Forensics",
         "A doctor–patient relationship with the parent forms when you treat the parent (relationship advice in their own session). Consenting for the child, family therapy with the child as patient, and collateral about the child's care do not make the parent your patient. Teaching point: Advice to the parent as the identified problem = you just took them on."),
    172: ("Psychopathology",
         "Melancholic features are more common in adolescent than child MDD. Irritability, somatic complaints, and hallucinations are at least as common (often more) in younger children. Teaching point: Teen depression looks more melancholic than child depression."),
    173: ("Assessment",
         "'Which movie character are you?' is a projective question (self onto a stimulus). Engagement, interactive play, and direct questions are other interview moves. Teaching point: Character identification = projective."),
    174: ("Neuroscience",
         "Empiric sibling recurrence risk for ASD after one affected child is on the order of 2–10% (higher if multiple affected, male, or a known variant). 20–90% would be Mendelian. Teaching point: Next-child ASD risk after one child ≈ 2–10%."),
    175: ("Psychopharmacology",
         "Relative to adults, youth on clozapine are keyed here as more likely to get akathisia (the vignette's falling ANC is a separate monitoring fact). Sialorrhea, weight, constipation, and hypotension occur in both ages; the exam's contrast is akathisia. Teaching point: Watch restlessness as well as ANC on pediatric clozapine."),
    176: ("Psychopharmacology",
         "Among listed agents, lithium has been used to treat antipsychotic/clozapine-associated akathisia. Carbamazepine, oxcarbazepine, lamotrigine, and valproate are not akathisia treatments. Teaching point: Clozapine akathisia option on a mood-stabilizer list = lithium."),
    177: ("Consultation & Schools",
         "Collaborative-care consultant's first move when PHQ-9 is stuck on fluoxetine 20 + weekly CBT is to ask why (adherence, dose, residual stressors) — not immediately augment, switch, IOP, or extra family education. Teaching point: Treat-to-target starts with 'why isn't this working?'"),
    178: ("Consultation & Schools",
         "Reviewing the whole caseload to find who is not improving is population-based care. Accountability, EBM, patient-centeredness, and measurement-based treat-to-target are other collaborative-care principles (MBC is the PHQ-9 itself). Teaching point: Caseload registry review = population-based care."),
    179: ("Neuroscience",
         "Short, obese, hypersomnolent, skin-picking, learning problems, and compulsive ordering is Prader–Willi; daytime somnolence plus obesity → order PSG for OSA (not EEG/EMG/MRI/MSLT first). Teaching point: PWS with sleepiness → sleep study."),
    180: ("Neuroscience",
         "Prader–Willi is loss of paternal 15q11–13 (paternal deletion or maternal uniparental disomy 15). The keyed inheritance pattern is maternal disomy of chromosome 15. Not AD, triplet repeat, XR, or 22q. Teaching point: PWS genetics to remember = maternal UPD 15 (or paternal 15q deletion)."),
    181: ("Consultation & Schools",
         "School connectedness is a daily in-school person who checks in — not sending records, rushing an IEP, assigning a school therapist, or starting CBITS (this was not a trauma admission). Teaching point: Connectedness = one named adult at school every day."),
    182: ("Psychopharmacology",
         "Fluoxetine is chosen because it has the strongest pediatric MDD evidence (TADS and others), not because it is cheapest, safest, or uniquely FDA-approved (escitalopram is also approved) or because head-to-head trials prove it most efficacious. Teaching point: Kid MDD SSRI with the best evidence = fluoxetine."),
    183: ("Psychotherapy",
         "For adolescent MDD, CBT has the most evidence (often combined with fluoxetine). Family therapy, DBT, psychodynamic, and IPT have roles but are not the best-supported here. Teaching point: Youth MDD therapy with the most data = CBT."),
    184: ("Neuroscience",
         "Complex-partial (focal impaired-awareness) auras include jamais vu, overwhelming fear, and olfactory hallucination. Lip smacking, circling, gelastic bursts, drowsiness, and LOC are ictal/post-ictal phenomena, not auras. Teaching point: Aura = psychic/sensory warning; automatisms are the seizure."),
    185: ("Psychopathology",
         "AMPD criterion A for adolescent borderline-range personality is impairment in identity, interpersonal functioning (social dysfunction), and affective dysregulation. Self-injury, anxiety, rigidity, psychosis, and somatic preoccupation are associated, not the three core dimensions. Teaching point: AMPD borderline core = identity + interpersonal + affect."),
    186: ("Psychopharmacology",
         "CYP2D6 poor metabolizers accumulate risperidone, aripiprazole, and perphenazine. Lurasidone/quetiapine/olanzapine/haloperidol/clozapine use other primary pathways (3A4, 1A2, etc.). Teaching point: 2D6 PM → go easy on risperidone, aripiprazole, perphenazine."),
    187: ("Neuroscience",
         "Epigenetic mechanisms: DNA methylation, histone modification, and noncoding-RNA post-transcriptional regulation. Chromatin elongation, inversions/translocations, DNase cleavage, and nucleotide substitution are not epigenetic regulation. Teaching point: Epigenetics = methylate, histone-mark, or microRNA — not a mutation."),
    188: ("Systems & Prevention",
         "IOM Crossing the Quality Chasm six aims: safe, effective, patient-centered, timely, efficient, equitable. Inexpensive, intuitive, standardized, integrated, and transcultural are not the six. Teaching point: STEEEP — safe, timely, effective, efficient, equitable, patient-centered."),
    189: ("Development",
         "Chess and Thomas: easy, difficult, and slow-to-warm-up. Stable/neutral/reactive/avoidant/hyperactive are not their three clusters. Teaching point: Infant temperament triad = easy / difficult / slow to warm up."),
    190: ("Neuroscience",
         "Benign Rolandic (centrotemporal) epilepsy: nocturnal seizures, remits by puberty, and can leave cognitive problems despite the 'benign' name. It is not hippocampal, not typically before age 3, often needs no meds, does not cause permanent behavioral disease, and usually has no LOC. Teaching point: BRE = night seizures that grow out by puberty, not always cognitively silent."),
    191: ("Psychotherapy",
         "Operant conditioning's core is ABC: antecedent, identified behavior, consequence. Time-out is one technique; morality, homework, attachment, and DT are not the operant triad. Teaching point: PMT is ABC — antecedent, behavior, consequence."),
    192: ("Neuroscience",
         "The salience network that tags incoming cognitive/emotional/homeostatic signals is keyed as insula, anterior cingulate, and ventromedial prefrontal cortex. Medial PFC/PPC and PCC are more default-mode; DLPFC and lateral PPC more executive. Teaching point: Salience = insula + ACC (+ vmPFC on this exam)."),
    193: ("Development",
         "Preschool shared pretend needs negotiation, perspective-taking, and some recognition of rules. Reputation, moral reasoning, respect for authority, ambivalence, and identification with the aggressor are later or different. Teaching point: Jungle pretend runs on negotiating, taking roles, and remembering the game's rules."),
    194: ("Ethics & Forensics",
         "HIPAA TPO allows treatment communications without extra authorization: consult the pediatrician, send a d/c summary to the outpatient psychiatrist, coordinate with the patient's other therapist. Nanny, school, sibling, and the parent's psychiatrist are not TPO. Teaching point: TPO = treaters of this patient, not the school or the family."),
    195: ("Neuroscience",
         "The exam keys Lesch–Nyhan, Rett, and Fragile X as the X-linked set. Lesch–Nyhan (HPRT) is the classic X-linked recessive; Rett (MECP2) and Fragile X (FMR1) are X-linked (Rett typically dominant/male-lethal; Fragile X is X-linked with unusual penetrance). Gaucher, PKU, and AT are autosomal recessive. Angelman/PWS are 15q imprinting. Teaching point: X-linked trio they want = Lesch–Nyhan, Rett, Fragile X."),
    196: ("Psychopathology",
         "Watching others undress = voyeuristic; stealing shoes for sexual arousal = fetishistic; cross-dressing with arousal = transvestic. Not pedophilic, frotteuristic, exhibitionistic, or sadism/masochism. Teaching point: Three paraphilias can stack: look, fetish object, transvestic arousal."),
    197: ("Psychopharmacology",
         "CYP2C19 poor metabolizers need lower doses of citalopram, escitalopram, and sertraline. Fluoxetine/paroxetine/fluvoxamine/duloxetine/nortriptyline are primarily 2D6 (or other) stories. Teaching point: 2C19 PM → cut the citalopram, escitalopram, sertraline."),
    198: ("Psychopathology",
         "The most common psychiatric comorbidities of Tourette are ADHD, OCD, and learning disorders. Bipolar, CD, ASD, ID, and IED occur less often. Teaching point: TS triad of comorbidity = ADHD + OCD + LD."),
    199: ("Psychopathology",
         "Migraine is associated with depression, panic attacks, and bipolar/mania-spectrum symptoms. Paranoia, catatonia, avoidance, hallucinations, and hypervigilance are not the replicated psychiatric cluster. Teaching point: Migraine psych comorbidity = depression, panic, mania."),
    200: ("Assessment",
         "Low-BMI adolescent who fainted: initial medical screen is CBC, CMP, and ECG (anemia, electrolytes/refeeding risk, arrhythmia). Bone densitometry is later. Lipase, A1c, PT, and GGT are not the first three. Teaching point: Restricting athlete who faints → CBC, CMP, ECG tonight."),
}
