"""Topics and explanations for CPRITE 2023 Q1–50."""

META: dict[int, tuple[str, str]] = {
    1: ("Development",
        "Selective recognition of one's own name is keyed at nine months. Social smile and cooing live at six weeks to three months; at six months many infants turn to voice or any name-like sound but are not yet selective. Teaching point: Boards milestone for selective name recognition is nine months."),
    2: ("Psychopathology",
        "Heavy internet pornography use in adolescent males is associated with delayed ejaculation (partnered orgasm delayed or absent after high-dose visual stimulation). Erectile disorder, genito-pelvic pain, masochism, and low desire are not the linked dysfunction. Teaching point: Teen porn use maps to delayed ejaculation, not ED."),
    3: ("Research Methods",
        "Molecular cytogenetics (array/FISH/CNV) linking chromosomal lesions to psychiatric illness almost never lets a single study be conclusive: variants are rare, samples differ, and replication is required. Functional nonspecificity and shared genes are real limits but not the keyed weakness. Teaching point: One cytogenetic association study does not close the case."),
    4: ("Development",
        "Mahler's separation-individuation, especially the practicing subphase, is timed to upright locomotion: the toddler walks away and comes back. Sitting, standing, grasping, and talking are not the physical correlate she used. Teaching point: Mahler practicing = walking."),
    5: ("Psychotherapy",
        "The child who witnessed domestic violence has the doll punch to get snacks: aggression acquired by watching (Bandura social learning). The snack grab can look operant, but the source of the script is modeled violence, not a reinforcement history you created in the room. Classical pairing and cognitive restructuring do not explain the reenactment. Teaching point: Witnessed violence replayed in play = social learning."),
    6: ("Psychopathology",
        "Brief autonomic attacks that occur only when the teen must speak or be with unfamiliar people, plus fear of embarrassment, are social anxiety disorder. Panic disorder needs unexpected attacks. Specific phobia is a circumscribed object. Separation anxiety is about attachment figures. GAD is pervasive worry, not performance cues. Teaching point: Cue = unfamiliar people/performance + embarrassment = social anxiety, even if it feels like panic."),
    7: ("Psychotherapy",
        "IPT-A keeps the adult problem areas but specifically discusses family structural change (divorce, reconstitution, the adolescent's shifting role at home). School refusal, abstract thinking, financial independence, and sexuality/gender identity are not IPT-A domains. Teaching point: IPT-A's adolescent-specific domain = family structural change."),
    8: ("Systems & Prevention",
        "Many non-Western societies frame suicide as a solution to a social or personal dilemma rather than as the product of a defined mental illness (the dominant Western medical model). Means availability, religious sanctions, and evolutionary stories are not the contrast being tested. Teaching point: Non-Western suicide is often a way out of a dilemma, not a disease."),
    9: ("Psychopharmacology",
        "ADHD with irritability and aggression still starts with a stimulant (methylphenidate); treating ADHD often drops the aggression. Divalproex and risperidone wait for stimulant failure, primary mania, or other indicated uses. Atomoxetine is second-line ADHD. Clonazepam is not a treatment for this picture. Teaching point: ADHD + aggression first-line = stimulant, not an antipsychotic."),
    10: ("Assessment",
        "In a preschooler, doll-play themes of hitting and 'you are bad'/'I hate you' are used to infer mood (anger, dysphoria) on the MSE. Thought content is the closest distractor and would be the right bucket in a verbal child reporting ideas, but this exam codes play theme as mood. Insight, cognition, and thought process are not what the aggressive script shows. Teaching point: Young-child play themes = MSE mood."),
    11: ("Neuroscience",
        "Incomplete penetrance means only some people who carry the disease-related gene show the phenotype. Locus heterogeneity is many genes, one phenotype. Polygenic inheritance is many loci. Phenocopies are nongenetic lookalikes. Mendelian genetics is a pattern of transmission, not variable expression. Teaching point: Gene present, disease only sometimes = incomplete penetrance."),
    12: ("Development",
        "Winnicott's core developmental idea is the infant-caretaker dyad as an emotionally facilitating (holding) environment. Psychoeducation, socialization, cultural assimilation, and regulation of expressed emotion belong to other frames. Teaching point: Winnicott = facilitating infant-caretaker dyad."),
    13: ("Ethics & Forensics",
        "Unencrypted email is for logistics: arranging appointment times. It is not for daily mood monitoring, starting a doctor-patient relationship, medication-change recommendations, or emailing a guardian clinical concerns about a teenager. Teaching point: Clinical email = scheduling, not care."),
    14: ("Research Methods",
        "Generalizability is external validity (do these results apply outside the sample?). Internal validity is whether the causal claim is clean inside the study. Reliability is consistency of a measure. Clinical significance and NNT describe magnitude, not transportability. Teaching point: Can I use this in my clinic? → external validity."),
    15: ("Ethics & Forensics",
        "When a psychiatrist is subpoenaed as a fact witness, reimbursement for time is not allowed. Negotiating an hourly rate is expert-witness practice. A court flat fee, billing insurance, and charging the patient are not the rule this item tests. Teaching point: Fact witness: you do not bill for your time."),
    16: ("Neuroscience",
        "Psychosis in epilepsy is associated with pathology in temporo-limbic structures (temporal lobe/limbic networks). Parietotemporal cortex, ventromedial frontal lobe, tuberoinfundibular region, and occipito-temporal circuits are not the classic pairing. Teaching point: Epileptic psychosis → temporo-limbic."),
    17: ("Development",
        "Holding a comforting caregiver image during an aggressive outburst so the child can self-regulate is object constancy. Theory of mind is attributing mental states. Reaction formation is a defense. Concrete operations is Piaget. Rapprochement is Mahler's coming-and-going subphase, not the internalized capacity. Teaching point: Angry and still holding a good parent inside = object constancy."),
    18: ("Systems & Prevention",
        "Higher rates of psychotic-disorder diagnoses in African-American/Black youth versus White youth are best explained by structural racism (mislabeling of mood, trauma, and behavioral presentations; biased systems). Ethnic difference, poverty, prenatal exposure, and genetic vulnerability do not account for the diagnostic gap. Teaching point: Black youth + psychosis label → think structural racism, not genes."),
    19: ("Neuroscience",
        "Cribriform-plate injury shears olfactory filaments (CN I). Identifying peppermint smell tests that nerve. Gag is IX/X, eyelid strength VII, tongue XII, jaw V. Teaching point: Cribriform plate → smell the mint."),
    20: ("Psychotherapy",
        "The garage door was paired with the abuser, so the sound alone elicits hiding even though hiding never prevented abuse and the parent is gone: classical conditioning. Operant learning would require the hide to have been reinforced. Learned helplessness is giving up, not a cue-triggered run to the closet. Incentive learning and contingency management are the wrong models. Teaching point: A fear cue that never had to 'work' = classical conditioning."),
    21: ("Assessment",
        "Language laterality and eloquent-cortex mapping before epilepsy surgery is functional MRI, the study that addresses the family's fear of language loss. DTI shows tracts, MRA vessels, MRS metabolites, and CSF-flow studies hydrocephalus. Teaching point: Family worried about language loss after epilepsy surgery → fMRI."),
    22: ("Psychopharmacology",
        "Caffeine increases lithium clearance and lowers the serum level. Ibuprofen and hydrochlorothiazide raise lithium. Amiloride is used in lithium diabetes insipidus, not to drop the level. Alprazolam does not lower lithium. Teaching point: Caffeine lowers lithium."),
    23: ("Systems & Prevention",
        "Among the listed options, random roadside drug testing is the keyed harm-reduction intervention for adolescent alcohol use (reducing drink-driving harm). Sales restrictions and mass-media campaigns are prevention. Motivational interviewing and peer self-help are treatment/support, not harm reduction as this item uses the term. Teaching point: Boards' adolescent alcohol harm reduction = random roadside testing."),
    24: ("Psychotherapy",
        "Timeout after homework screaming lets the child escape the task, so the scream is negatively reinforced. The effective move is to ignore the scream and redirect back to the work (extinction plus task continuation). Ending the task, more timeout, reassurance, or a token after the scream all feed the behavior. Teaching point: Escape-maintained scream → ignore and return to the work."),
    25: ("Assessment",
        "Infant mental-status assessment uniquely includes watching feeding behaviors (alertness, engagement, regulation at breast or bottle). Speech is not available. Hyperactivity, affect regulation, and dysmorphic features can be noted at any age and are not the infant-specific MSE component. Teaching point: Infant MSE = watch them feed."),
    26: ("Psychotherapy",
        "A young child with PTSD and poor attachment needs an evidence-based dyadic, manualized treatment: dyadic parent-child interaction therapy, which has shown affect-regulation gains. Unstructured play therapy, family psychodynamic therapy, multidimensional family therapy, and self-regulation-focused CBT are not the keyed intervention. Teaching point: Little kid, trauma, weak attachment → dyadic parent-child work."),
    27: ("Neuroscience",
        "Neuronal connectivity in neurodevelopmental disabilities is assessed with diffusion tensor imaging (white-matter tracts). CT and conventional MRI show structure, PET metabolism, and MRS chemistry. Teaching point: Connectivity question → DTI."),
    28: ("Psychopathology",
        "The most common method of completed suicide in youth ages 10-14 is suffocation (hanging). Poisoning and cutting dominate nonfatal attempts more than completions in this band; jumping and electrocution are not the leading method. Teaching point: Preteen/early-teen completion = hanging/suffocation."),
    29: ("Psychopathology",
        "A five-day run of irritability with decreased need for sleep, goal-directed overnight organizing, school talkativeness, and provocative dress is a manic/hypomanic episode: bipolar disorder. Cyclothymia needs a year of subthreshold swings. DMDD is chronic, not episodic. ODD and ADHD lack the decreased-need-for-sleep package. Teaching point: Days-long irritable high plus no-sleep energy = bipolar, not DMDD."),
    30: ("Psychopathology",
        "The personality disorder most frequently comorbid with bulimia nervosa is borderline. Avoidant, histrionic, narcissistic, and obsessive-compulsive PDs occur, but OCPD is the more classic pairing with restricting anorexia, not BN. Teaching point: BN + personality disorder → borderline."),
    31: ("Psychopharmacology",
        "First-line disease-modifying therapy for pediatric multiple sclerosis is interferon (IFN-beta). Prednisone treats acute relapses, not as DMT. Natalizumab, mitoxantrone (Novantrone), and cyclophosphamide are escalation or aggressive-disease agents, not first-line in children. Teaching point: Pediatric MS DMT first-line = interferon."),
    32: ("Ethics & Forensics",
        "Offering $100 to adolescents who complete a study, the live ethical issue is vulnerability to coercion/undue influence. Payment can be ethical if not coercive. Parental consent is required but is not the most important factor here. Mental illness does not equal incompetence, and control groups are a design question. Teaching point: Paying teens → watch for coercion, not a ban on payment."),
    33: ("Systems & Prevention",
        "Chronic anorexia, HR 60 and BP 100/80 (not medically crashing), unable to hold weight despite family and outpatient care, plus school collapse: residential treatment. A medical hospital is for physiologic instability. General inpatient psychiatry often lacks refeeding protocols. Partial hospital and intensive outpatient assume the child can still live at home with stepped-up hours. Teaching point: Failed-outpatient AN, medically okay → residential, not a medical bed."),
    34: ("Ethics & Forensics",
        "AACAP policy: isolation for more than 24 hours as discipline for youth in a correctional facility is strongly discouraged in all cases. It is not justified by agitation, severe aggression, preference over medication, or a child psychiatrist's order. Teaching point: >24h isolation of locked-up youth = no."),
    35: ("Psychopharmacology",
        "Risperidone-related galactorrhea with confirmed hyperprolactinemia (pregnancy negative) is managed by switching to aripiprazole, a partial D2 agonist that lowers prolactin. Lurasidone is also relatively sparing but is not the keyed switch. Bromocriptine, lorazepam, and benztropine do not fix antipsychotic hyperprolactinemia. Teaching point: Risperidone milk → switch to aripiprazole."),
    36: ("Psychopathology",
        "Substance-induced psychosis converts to schizophrenia most often after cannabis. Stimulant (amphetamine/cocaine) and hallucinogen psychoses can look florid in the moment but have weaker later-schizophrenia links; alcohol is the weakest of the list. Teaching point: Cannabis-induced psychosis is the one that most often becomes schizophrenia."),
    37: ("Neuroscience",
        "Acute stress raises plasma interleukin-6. Monocytes, CD4+ cells, B lymphocytes, and TNF-alpha are not the keyed acute plasma spike. Teaching point: Acute-stress cytokine = IL-6."),
    38: ("Psychotherapy",
        "The central CBT component for needle phobia is graduated exposure to needles. Processing the emotion, thought records, recognizing the fear as irrational, and examining distortions can adjunct; exposure is the active ingredient in specific phobia. Teaching point: Needle fear → hierarchical exposure."),
    39: ("Consultation & Schools",
        "Under IDEA, a manifestation determination review is required when a change of placement is more than ten days. It is not triggered by communication, language, sensory, or medical disability category alone, and not by every disciplinary action regardless of length. Teaching point: MDR = placement change >10 days."),
    40: ("Assessment",
        "Flattened affect supports schizophreniform disorder over epileptiform psychosis. Hallucinations, depersonalization, persecutory delusions, and disorganized behavior occur in both; negative symptoms are the discriminator. Teaching point: Flat affect → schizophrenia-spectrum, not seizure psychosis."),
    41: ("Neuroscience",
        "Childhood sexual abuse most conclusively alters glucocorticoid-receptor expression via epigenetic modification (NR3C1). NMDA, serotonin 1A, D2, and ACTH receptors are not the landmark finding. Teaching point: Abuse epigenetics = glucocorticoid receptor."),
    42: ("Systems & Prevention",
        "Greater childhood exposure to green space is associated with lower risk of psychiatric disorder in adulthood. Same-sex parents, apartment living, non-religious family, and urban environment are not protective factors in this literature. Teaching point: More green space in childhood, fewer adult psychiatric diagnoses."),
    43: ("Psychopharmacology",
        "In the TEA trial, antipsychotic-related weight change at two weeks predicted later weight gain. Weight is not independent of regimen, not simply a dose effect, not expected to return to baseline, and not defined by a 10% plateau. Teaching point: Two-week weight bump predicts the later bump."),
    44: ("Research Methods",
        "Assigning whole schools by lottery to intervention versus control is cluster randomization (the unit of randomization is the cluster). Factorial crosses two manipulations. Crossover gives each unit both conditions. Time series is before-after. Comparative effectiveness compares actives without this clustering. Teaching point: Randomize schools, not kids = cluster RCT."),
    45: ("Neuroscience",
        "Appetite rises when leptin falls (low adipose stores remove the satiety signal). Ghrelin, orexin, and neuropeptide Y increase appetite when they rise, so they fail the 'decreases then hungry' test. Cortisol is not the keyed satiety hormone. Teaching point: Low leptin = hungry."),
    46: ("Psychopathology",
        "Childhood functional abdominal pain is most closely associated with maternal anxiety and depression. Male gender, parental neglect, ADHD, and absence of anxiety in the child are not the linked factors (the children often are anxious too). Teaching point: Functional bellyaches in the child ↔ anxiety/depression in the mother."),
    47: ("Consultation & Schools",
        "In ABCD, among students with similar externalizing behavior, Black race had the greatest adjusted odds of detention or suspension, above older age, single caregiver, low parental education, and special education services. Teaching point: Same behavior, Black students get suspended more."),
    48: ("Neuroscience",
        "The suprachiasmatic nucleus receives retinal (retinohypothalamic) input and runs diurnal/circadian rhythms. Arcuate is appetite, supraoptic ADH/oxytocin, ventromedial satiety, paraventricular HPA/autonomic. Teaching point: Retina → SCN → clock."),
    49: ("Neuroscience",
        "Selective face processing lives in the lateral fusiform gyrus (fusiform face area), a region implicated in ASD social-perception models. Thalamus, hippocampus, prefrontal cortex, and corpus callosum are not the face module. Teaching point: Faces in ASD → lateral fusiform (FFA)."),
    50: ("Systems & Prevention",
        "Parenting practices mediate the effect of both socioeconomic status and neighborhood on adolescent conduct disorder. Peer violence, school climate, intelligence, and temperament matter, but they are not the keyed mediators of both SES and neighborhood. Teaching point: Poverty/neighborhood → conduct disorder via parenting."),
}
