// Assemble the per-batch context outputs into (1) a canonical JSON artifact and
// (2) a Supabase data migration that upserts into question_context.
//
// Run AFTER the generation workflow finishes:  node extraction/context_gen/assemble.mjs
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const outDir = join(here, "out");

// Every question id we expect, so we can report coverage gaps.
const all = JSON.parse(readFileSync(join(root, "extraction/output/questions_all.json"), "utf8"));
const expected = new Set(all.map((q) => `${q.year}-${q.q_index}`));

const map = new Map();
let files = 0, bad = [];
for (const f of readdirSync(outDir).filter((f) => /^batch_\d+\.json$/.test(f)).sort()) {
  files++;
  let arr;
  try { arr = JSON.parse(readFileSync(join(outDir, f), "utf8")); }
  catch (e) { bad.push(`${f}: ${e.message}`); continue; }
  if (!Array.isArray(arr)) { bad.push(`${f}: not an array`); continue; }
  for (const r of arr) {
    if (r && typeof r.id === "string" && typeof r.context === "string" && r.context.trim()) {
      map.set(r.id, r.context.trim());
    }
  }
}

const missing = [...expected].filter((id) => !map.has(id));
const extra = [...map.keys()].filter((id) => !expected.has(id));

console.log(`read ${files} batch files`);
if (bad.length) console.log(`PARSE PROBLEMS (${bad.length}):\n  ` + bad.join("\n  "));
console.log(`contexts: ${map.size} / ${expected.size} expected`);
if (missing.length) console.log(`MISSING ${missing.length}: ${missing.slice(0, 40).join(", ")}${missing.length > 40 ? " ..." : ""}`);
if (extra.length) console.log(`UNEXPECTED ids ${extra.length}: ${extra.slice(0, 10).join(", ")}`);

// 1) canonical JSON (sorted for stable diffs)
const obj = {};
for (const id of [...map.keys()].sort()) obj[id] = map.get(id);
writeFileSync(join(root, "extraction/output/question_context.json"), JSON.stringify(obj, null, 0));
console.log(`wrote extraction/output/question_context.json (${map.size} rows)`);

// 2) Supabase data migration (chunked multi-row upserts)
const esc = (s) => s.replace(/'/g, "''");
const rows = [...map.entries()].sort((a, b) => a[0].localeCompare(b[0]));
const CHUNK = 400;
let sql = `-- Auto-generated by extraction/context_gen/assemble.mjs.\n`;
sql += `-- Upserts ${rows.length} historical-context blurbs into question_context.\n`;
sql += `-- Requires 0013_question_context.sql (the table) to have run first.\n\n`;
for (let i = 0; i < rows.length; i += CHUNK) {
  const chunk = rows.slice(i, i + CHUNK);
  sql += `insert into question_context (question_id, context) values\n`;
  sql += chunk.map(([id, ctx]) => `  ('${esc(id)}', '${esc(ctx)}')`).join(",\n");
  sql += `\non conflict (question_id) do update set context = excluded.context, updated_at = now();\n\n`;
}
writeFileSync(join(root, "supabase/migrations/0014_question_context_data.sql"), sql);
console.log(`wrote supabase/migrations/0014_question_context_data.sql`);

console.log(missing.length ? `\nDONE WITH GAPS — re-run the missing batches before deploying.` : `\nDONE — full coverage.`);
