#!/usr/bin/env python3
"""Find explanations whose SOURCE contained a table, and report what happened to it.

Many explanations were OCR'd from slides that showed a comparison table. OCR flattens a table into
column-interleaved word salad, so the reformatting pass either rendered it as bullets, dropped it as
unreadable, or (worst case) reconstructed it with values attached to the wrong row.

The app already renders a proper table from the `comparison_table` field (App.tsx ~2193), and 920
questions have one. So a question whose explanation lost its table but has no comparison_table is a
genuine content regression, and the fix is to populate that field rather than to inline more bullets.

  python3 extraction/audit_tables.py            # summary
  python3 extraction/audit_tables.py --list     # per-question detail
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
BANK = BASE / "extraction" / "output" / "questions_all.json"
ORIG = BASE / "extraction" / "output" / "questions_all.json.bak-prefmt-trial"

# Signals that the OCR'd source was rendering a table rather than prose.
TABLE_SIGNALS = [
    (re.compile(r"\bTable\s+\d", re.I), "explicit 'Table N'"),
    (re.compile(r"\b(Feature|Drug|Class|Mechanism|Indication|Finding|Option|Criterion|Term)\s+"
                r"(Class|Mechanism|Indication|Effect|Route|Why|Key|Core|Typical|Main)\b"), "adjacent column headers"),
    (re.compile(r"\b(Stage indicated|Dosage titration|Side [Ee]ffects?\s+\w+\s+\w+\s+Route)\b"), "drug-table headers"),
    (re.compile(r"(?:^|\n)\s*\|"), "pipe-delimited row"),
    (re.compile(r"\b\w+\s+VMAT2\s+\w+.*\bVMAT2\b", re.S), "repeated class column"),
]


def flattened_run(text: str, formatted: bool = False) -> tuple[int, int]:
    """Longest stretch with no sentence-ending punctuation, and how many capitalised words it holds.

    This is the load-bearing signal. OCR flattens a table by concatenating cells, so a table shows
    up as an enormous "sentence" full of Title-Case fragments: measured at 66-351 words with 5-99
    capitalised starts on known table items, versus <=49 words and <=3 caps on ordinary prose.
    Header keywords alone missed 4 of 9 known cases, which is why this exists.
    """
    # Split on bullets and line breaks as well as sentence punctuation. A correctly restructured
    # table is a bullet list, and bullet lines rarely end in a period — measuring only on [.!?]
    # scores a clean list as one enormous "run" and reports the fix as still broken.
    # Asymmetric on purpose. In OCR'd SOURCE text a bullet is itself an artifact and splitting on it
    # would hide a real flattened table, so only sentence punctuation counts. In FORMATTED output the
    # bullets are real structure, and not splitting on them scores a clean list as one giant run.
    sep = r"[.!?]\s|\n|•" if formatted else r"[.!?]\s"
    best = best_caps = 0
    for seg in re.split(sep, text or ""):
        w = seg.strip().split()
        if len(w) < 18:
            continue
        caps = sum(1 for x in w[1:] if re.match(r"^[A-Z][a-z]", x))
        if len(w) > best or (len(w) == best and caps > best_caps):
            best, best_caps = len(w), caps
    return best, best_caps


def table_evidence(text: str) -> list[str]:
    why = [w for rx, w in TABLE_SIGNALS if rx.search(text or "")]
    run, caps = flattened_run(text)
    if run >= 55 and caps >= 5:
        why.append(f"flattened run ({run}w, {caps} capitalised)")
    return why


def main() -> None:
    detail = "--list" in sys.argv
    new = {f'{q["year"]}-{q["q_index"]}': q for q in json.loads(BANK.read_text())}
    old = {f'{q["year"]}-{q["q_index"]}': q for q in json.loads(ORIG.read_text())}

    # The `comparison_table` and `diagram` fields were generated by a separate AI pass and are NOT a
    # recovery of the OCR'd table, so they do not count as the table having survived. What matters is
    # whether the flattened string in explanation_text came out readable.
    buckets: dict[str, list] = {
        "restructured into bullets (readable)": [],
        "still a flattened wall of text": [],
        "table content dropped": [],
    }
    for qid, q in new.items():
        src = old[qid].get("explanation_text") or ""
        why = table_evidence(src)
        if not why:
            continue
        cur = q.get("explanation_text") or ""
        n_bullets = cur.count("\n•")
        run_after, caps_after = flattened_run(cur, formatted=True)
        src_words = len(src.split())
        if n_bullets >= 3 and run_after < 55:
            buckets["restructured into bullets (readable)"].append((qid, why, n_bullets))
        elif run_after >= 55 and caps_after >= 5:
            buckets["still a flattened wall of text"].append((qid, why, n_bullets))
        elif len(cur.split()) < src_words * 0.6:
            buckets["table content dropped"].append((qid, why, n_bullets))
        else:
            buckets["restructured into bullets (readable)"].append((qid, why, n_bullets))

    total = sum(len(v) for v in buckets.values())
    print(f"explanations whose source shows table structure: {total}\n")
    for k, v in buckets.items():
        print(f"  {len(v):>4}  {k}")
    lost = buckets["still a flattened wall of text"] + buckets["table content dropped"]
    if lost:
        print(f"\nquestions whose OCR'd table did NOT come out readable ({len(lost)}):")
        for qid, why, nb in (lost if detail else lost[:25]):
            print(f"    {qid:>10}  bullets={nb:<3} evidence: {', '.join(why)}")
        Path(BASE / "extraction" / "output" / "_fmt" / "tables_lost.json").write_text(
            json.dumps([q for q, _, _ in lost], indent=1))
        print(f"\n  ids written to extraction/output/_fmt/tables_lost.json")


if __name__ == "__main__":
    main()
