"""Psychodynamic perspectives for a senior resident in a psychodynamic program.

Cores are 3–4 sentences in the zone of proximal development: enactment,
projective identification, frame, negative therapeutic reaction, levels of
organization — not dictionary definitions of transference. Citations are
optional; the fox does not display them.
"""

PEARLS = [
    {
        "id": "transference",
        "fallback_for": ["psychotherapy"],
        "core": "The useful question is not whether transference is happening — it always is — but which object you have been recruited to become, and what the patient is trying to do to that object. Notice the moment you start answering from inside the role, the reassuring parent or the withholding judge, rather than noticing you have been cast. That noticing is already interpretive work, even if you never say it aloud. If you only interpret history and ignore the live recruitment, you will have a clever formulation and a stuck treatment.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["transference", "as if you were", "reminds the patient"],
    },
    {
        "id": "countertransference",
        "fallback_for": ["psychotherapy"],
        "core": "Treat your irritation, rescue fantasy, or sudden stupidity as clinical data about an induced role, not as a personal failure to be suppressed. Ask: what is the patient needing me to carry so they do not have to know it? The complementary identification is often more informative than the concordant one. If you act from the feeling before you can think it, you have already entered the enactment.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["countertransference", "your own feelings", "therapist feels"],
    },
    {
        "id": "enactment",
        "fallback_for": ["psychotherapy"],
        "core": "An enactment is not the patient's acting out plus your mistake. It is a two-person repetition that neither of you can think until it has already been staged. The technical task is to survive it without retaliation or collapse, then describe the scene from inside it. Premature interpretation of the patient's history, offered to get yourself out of the discomfort, usually deepens the enactment.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["enactment", "acting in", "two-person", "staged"],
    },
    {
        "id": "projective-id",
        "core": "Projective identification is not just a misattribution. It is an interpersonal pressure that recruits you to feel, and often to behave, as the disavowed part. The diagnostic clue is a feeling that seems too large, too sudden, or too unlike you. If you only interpret the projection and never metabolize the induced state, the patient experiences you as handing the hot object back untouched.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["personality-disorder"],
        "topics": ["Psychotherapy & Psychodynamics", "Personality Disorders"],
        "categories": ["psychotherapy"],
        "keywords": ["projective identification", "induced", "you found yourself"],
    },
    {
        "id": "splitting",
        "core": "Splitting is not mere black-and-white thinking. It is a failure to hold that the same object can gratify and frustrate, which protects against the depressive-position work of ambivalence and guilt. In the room it shows up as sudden idealization or devaluation that does not survive overnight. Interpreting the content of the good or bad picture is less useful than naming the switch itself, and your own urge to become consistently one or the other.",
        "psychotherapy": ["psychodynamic", "dbt"],
        "diagnoses": ["personality-disorder"],
        "topics": ["Personality Disorders", "Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["splitting", "all good", "all bad", "idealiz", "devalu"],
    },
    {
        "id": "kernberg-bpd",
        "core": "Kernberg's level of organization is a more useful first cut than the DSM count of criteria. Identity diffusion, primitive defenses, and generally intact reality testing tell you that clarification and confrontation of the here-and-now relation will outperform genetic reconstruction. Watch whether the patient can use a transference observation or only experience it as an attack. That distinction, more than the history of self-harm, tells you how much structure the treatment will need.",
        "psychotherapy": ["psychodynamic", "dbt"],
        "diagnoses": ["personality-disorder"],
        "topics": ["Personality Disorders"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["identity diffusion", "borderline organization", "kernberg", "reality testing intact"],
    },
    {
        "id": "kohut-mirroring",
        "core": "A Kohutian listen asks whether the grandiosity is a defense against envy or an arrested developmental need that still requires a mirroring or idealizing selfobject. The technical implication is opposite to a purely Kernbergian confrontation of omnipotence. If you deflate a selfobject transference too early, you get rage that looks like entitlement and is actually a fragmenting injury. The question is whether the shine can survive an ordinary disappointment, not whether the patient is 'really' narcissistic.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["personality-disorder"],
        "topics": ["Personality Disorders", "Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["mirroring", "idealizing transference", "twinship", "kohut", "narciss"],
    },
    {
        "id": "negative-therapeutic",
        "core": "A negative therapeutic reaction is getting worse after a good piece of work, not merely a bad week. One lineage hears unconscious guilt and a need for punishment; another hears envy of the helping object that must be spoiled. Either way, more of the same interpretation will be experienced as the analyst triumphing. The move is to take up the attack on the help itself, including your own wish to prove that the last hour was useful.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["negative therapeutic", "worse after insight", "unconscious guilt"],
    },
    {
        "id": "frame",
        "fallback_for": ["psychotherapy", "practice_issues"],
        "core": "The frame is not a house rule you enforce when irritated. It is the reliably frustrating structure that makes regression usable instead of merely chaotic. When the patient presses the time, the fee, or the extra email, they are often testing whether you can be used as a containing object or only as a gratifying one. A collapsed frame masquerading as flexibility usually produces a treatment that feels warm and goes nowhere.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics", "Forensic Psychiatry & Ethics"],
        "categories": ["psychotherapy", "practice_issues"],
        "keywords": ["frame", "boundary", "fee", "session time", "confidentiality"],
    },
    {
        "id": "resistance",
        "core": "Resistance is not the patient being difficult. It is the ego's current best solution, and it will reappear in the transference as soon as you get near the warded-off material. Interpreting the resistance before the alliance can hold it is experienced as a demand to surrender the solution. Better to describe how the late arrival, the charming detour, or the sudden intellectualization is protecting something still unthinkable.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["resistance", "changes the subject"],
        "anchors": ["resistance"],
    },
    {
        "id": "neutrality",
        "core": "Neutrality is equidistance from the conflict, not warmth withheld as a technique. When you take the side of the healthy ego against the symptom too quickly, you have joined the patient's own war on a part of the self. The same is true if you silently side with the id against a harsh superego. The work is to keep both parties in the room long enough for a new settlement.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["neutrality", "abstinence", "anonymous", "blank screen"],
    },
    {
        "id": "interpretation",
        "core": "An interpretation that is true and mistimed is not a near-miss. It is an enactment of knowing better. Clarification and confrontation prepare a surface the patient can stand on; working-through is the boring repetition after the first 'aha.' If you find yourself delivering a beautiful genetic reconstruction while the patient is in a fragmented or paranoid state, you are lecturing a part that cannot use it.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["interpretation", "clarification", "confrontation", "working through"],
    },
    {
        "id": "therapeutic-split",
        "core": "Without an observing ego that can ally with you, interpretation is just another argument the patient has already lost at home. The first technical task is often to build that split — 'a part of you notices' — rather than to uncover deeper content. In more primitive organizations that split is intermittent and has to be reconstructed hour by hour. If you skip it, you will hear yourself getting sharper and the patient getting more concrete.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["observing ego", "therapeutic split", "ally with you"],
    },
    {
        "id": "mentalization",
        "core": "A mentalization failure is not the same as splitting, though they travel together. The patient cannot hold that their own state, or yours, is a representation rather than a fact. In that moment insight-oriented comments are experienced as gaslighting or as proof you do not see the danger. The move is to rewind to the break — what just happened between us — before you interpret the childhood scene it resembles.",
        "psychotherapy": ["psychodynamic", "dbt"],
        "diagnoses": ["personality-disorder"],
        "topics": ["Personality Disorders", "Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["mentaliz", "mbt", "holding mind", "fonagy"],
    },
    {
        "id": "tfp",
        "core": "Transference-focused work treats the dominant object relation in the hour as the royal road, not the childhood narrative. You name the polarity as it lives between you — the attacking child and the abandoning object, then the switch — and you do not soothe it away. The risk is a cold correctness that repeats the longed-for and hated authority. The discipline is to keep the affect in the room without becoming either pole.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["personality-disorder"],
        "topics": ["Personality Disorders"],
        "categories": ["psychotherapy"],
        "keywords": ["transference-focused", "tfp", "kernberg treatment"],
    },
    {
        "id": "winnicott-holding",
        "core": "Holding is not being nice. It is the unobtrusive reliability that lets a self form, including the capacity to be alone in your presence. Patients who cannot use interpretation often need a long stretch of this before any 'why' is metabolizable. The countertransference trap is to feel useless, or to start performing insight so you will have something to show for the hour.",
        "psychotherapy": ["psychodynamic", "supportive"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics", "Development & Lifespan"],
        "categories": ["psychotherapy", "development"],
        "keywords": ["holding environment", "good enough", "facilitating environment", "winnicott"],
        "anchors": ["winnicott", "holding environment", "good enough"],
    },
    {
        "id": "true-false-self",
        "core": "A compliant false self can look like an excellent patient: on time, grateful, psychologically minded, and somehow never quite there. The risk is that you analyze the persona and leave the hidden self untouched, which the patient experiences as another demand to perform. Watch for the session that feels oddly frictionless. That ease is often the false self doing the treatment for both of you.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["personality-disorder"],
        "topics": ["Psychotherapy & Psychodynamics", "Personality Disorders"],
        "categories": ["psychotherapy"],
        "keywords": ["false self", "true self", "compliance", "as-if personality"],
    },
    {
        "id": "transitional-object",
        "core": "The transitional object is not a stuffed animal trivia item. It is the first not-me possession, and it lives in a space you must not challenge with premature reality-testing. In adult treatments the extra email, the particular chair, or even the medication can occupy that space. If you interpret it away as 'just a defense,' you may be collapsing the only area in which play is still possible.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Development & Lifespan", "Child & Adolescent Psychiatry", "Psychotherapy & Psychodynamics"],
        "categories": ["development", "psychotherapy"],
        "keywords": ["transitional object", "security blanket", "teddy", "not-me"],
    },
    {
        "id": "klein-splitting",
        "core": "The paranoid-schizoid position is a way of organizing experience, not a diagnosis. Parts are kept apart so that the good object cannot be destroyed by the patient's own hate. Movement toward the depressive position is marked by concern, guilt that can be borne, and the wish to repair — not by becoming 'nicer.' If you only congratulate the patient on insight, you may miss that they have just become able to mourn.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["personality-disorder"],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["paranoid-schizoid", "depressive position", "klein", "whole object"],
    },
    {
        "id": "turning-against-self",
        "core": "Melancholia is not just sadness with low self-esteem. The shadow of the object falls on the ego, and the attacks you hear as self-reproach are often aimed at an internalized other the patient cannot afford to hate. Listen for the borrowed voice in the self-criticism. If you only mobilize behavioral activation against that voice, you have sided with one half of an unfinished mourning.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["major-depression", "grief"],
        "topics": ["Mood Disorders", "Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["anger turned inward", "melancholia", "introject", "self-reproach", "worthlessness", "guilt"],
        "anchors": ["depression", "depressive", "melancholia", "worthlessness"],
    },
    {
        "id": "mourning-work",
        "core": "Mourning is slow decathexis, not a stage you complete. The work is to bear that the object is gone and that one's own hate and love both belonged to it. Melancholia short-circuits that by turning the attack inward so the object need not be given up. When a resident reaches for an SSRI at the first tear, ask whether you are treating a mood disorder or interrupting a necessary unbinding.",
        "psychotherapy": ["psychodynamic", "ipt"],
        "diagnoses": ["grief"],
        "topics": ["Mood Disorders"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["mourning", "grief work", "bereavement", "lost object"],
    },
    {
        "id": "mania-defense",
        "core": "A manic defense is not the same as a bipolar I episode, though they can coincide. It is a flight into activity, certainty, and contempt for need so that smallness and grief never have to be felt. In the hour it can look like sudden improvement, productivity, or a wish to taper everything. Before you congratulate the recovery, ask what just became unthinkable.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["bipolar"],
        "topics": ["Mood Disorders"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["mania as defense", "flight into health", "manic defense", "mania", "manic", "hypomania", "bipolar"],
        "anchors": ["mania", "manic", "hypomania", "bipolar"],
    },
    {
        "id": "signal-anxiety",
        "core": "Signal anxiety is the ego's early warning, a small dose that recruits defense before the forbidden impulse floods the system. Panic, in this register, is a failed signal — the alarm without a usable representation of the danger. The psychodynamic question is not 'what are they anxious about' but 'what wish or rage could not be bound in time.' Exposure can reduce the alarm; it does not automatically restore the signal function.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["gad", "panic", "phobia"],
        "topics": ["Anxiety, OCD & Trauma/PTSD"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["signal anxiety", "anxiety as signal", "panic", "phobia", "generalized anxiety"],
        "anchors": ["anxiety", "anxious", "panic", "phobia"],
    },
    {
        "id": "panic-focused",
        "core": "Panic-focused psychodynamic work hears the attack as a failed signal around separation, anger, or a forbidden sexual wish. The unconscious fantasy is often that someone will be destroyed if the feeling is known. Tracing that fantasy in the transference — what would happen to me if you got angry here — is more specific than generic grounding. Medication can lower the gain on the alarm while you do that work; it does not make the fantasy disappear.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["panic"],
        "topics": ["Anxiety, OCD & Trauma/PTSD"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["panic-focused", "pfpp", "separation", "panic attack meaning"],
    },
    {
        "id": "undoing",
        "core": "Undoing is not a habit. It is a magical reversal of a forbidden wish, which is why reassurance and extra checking never quite finish the job. The ritual is the patient's attempt to keep both the wish and the object alive. If you only block the ritual without making the wish thinkable, you will get a cleaner-looking patient and a displaced symptom.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["ocd"],
        "topics": ["Anxiety, OCD & Trauma/PTSD"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["undoing", "ritual", "checking", "washing", "take it back"],
    },
    {
        "id": "reaction-formation",
        "core": "Reaction formation is more than being 'too nice.' The opposing attitude has to be continuously performed or the original impulse returns, which is why it feels brittle. In OCD and in certain moralistic character styles, the analyst's job is not to unmask the hypocrisy but to make room for the hated wish without humiliation. Premature confrontation of the reaction formation often intensifies it.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["ocd"],
        "topics": ["Anxiety, OCD & Trauma/PTSD", "Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["reaction formation", "opposite", "overly kind", "ocd defense"],
    },
    {
        "id": "isolation-affect",
        "core": "Isolation of affect lets the patient tell you a horror in a flat voice and then ask a technical question. It is adaptive in a trauma surgeon and costly in an intimate life. Do not congratulate the composure too quickly. The work is to find the moment the feeling was split off, often in the room when you yourself felt more than they did.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["ocd"],
        "topics": ["Anxiety, OCD & Trauma/PTSD", "Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["isolation of affect", "intellectualization", "flat affect", "obsessional"],
    },
    {
        "id": "trauma-unassimilated",
        "core": "What cannot be remembered is repeated, and what cannot be represented is enacted in the body or in the dyad. The technical error is to hunt for the historical scene while the unassimilated bit is already happening between you. Slow the hour down at the moment of repetition, not after. Words come after a shared noticing, not as a substitute for it.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["ptsd", "dissociative"],
        "topics": ["Anxiety, OCD & Trauma/PTSD"],
        "categories": ["psychotherapy"],
        "keywords": ["ptsd", "posttraumatic", "post-traumatic", "flashback", "unassimilated", "remembering repeating", "combat", "assault"],
        "anchors": ["ptsd", "posttraumatic", "post-traumatic", "flashback", "combat"],
    },
    {
        "id": "dissociation",
        "core": "Dissociation is a vertical split in consciousness, not repression into the depths. The patient may leave the room without leaving the chair, and your beautifully timed interpretation lands in an empty seat. The first task is to notice the departure and help them return, not to reconstruct what they fled. If you keep interpreting through a dissociated state, you are analyzing a recording.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["dissociative"],
        "topics": ["Dissociative, Somatic Symptom & Eating Disorders"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["dissociation", "depersonalization", "derealization", "amnesia"],
    },
    {
        "id": "conversion",
        "core": "Even if you no longer need a conversion fantasy to make the functional-neuro diagnosis, the symptom still has a relational use. It can protect a forbidden wish, stabilize a dyad, or speak when speech would cost too much. The psychodynamic contribution is not to 'find the trauma' but to ask what the symptom is doing in this relationship today. A hunt for meaning that ignores the neurologic workup is as one-sided as a workup that treats meaning as noise.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["somatic-symptom", "dissociative"],
        "topics": ["Dissociative, Somatic Symptom & Eating Disorders"],
        "categories": ["psychotherapy", "consultation"],
        "keywords": ["conversion", "hysteria", "somatic compliance", "functional neurological"],
    },
    {
        "id": "addiction-object",
        "core": "From an object-relations angle the substance is a ruthlessly reliable other: it soothes, it does not leave, and it does not require mentalization. That is why insight about consequences so often fails at the moment of craving. The treatment has to become more reliable than the drug without becoming another omnipotent object to be defied. Watch the transference to the agonist, the group, and you — each can be used as a bottle.",
        "psychotherapy": ["psychodynamic", "motivational"],
        "diagnoses": ["substance-use"],
        "topics": ["Substance Use Disorders"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["self-medication", "soothing", "the bottle", "object substitute", "alcohol", "opioid", "cocaine", "heroin", "addiction", "substance abuse", "methadone", "buprenorphine", "drug abuse", "intravenous"],
        "anchors": ["alcohol", "opioid", "cocaine", "heroin", "addiction", "methadone", "drug abuse"],
    },
    {
        "id": "eating-control",
        "core": "Restriction can be a fight for ownership of a body that has been used, watched, or spoken for. The thinness is not the point; the inviolable territory is. If you only restore weight you may win a medical victory and confirm that the body still belongs to the institution. The psychodynamic work is to find whether any desire can be allowed without it becoming an invasion.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["anorexia", "bulimia"],
        "topics": ["Dissociative, Somatic Symptom & Eating Disorders"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["anorexia", "bulimia", "thinness", "restriction", "purging", "binge"],
        "anchors": ["anorexia", "bulimia", "binge"],
    },
    {
        "id": "psychosis-boundary",
        "core": "In a psychotic organization the stimulus barrier and the self–object boundary are unreliable, so genetic interpretation is often experienced as penetration. Supportive work here is not a lesser therapy. It is the active restoration of walls — reality testing offered as a shared ego, not as a correction. If you feel an urgent need to decode the delusion, ask whether you are trying to make yourself feel like an analyst.",
        "psychotherapy": ["supportive", "psychodynamic"],
        "diagnoses": ["schizophrenia", "psychosis"],
        "topics": ["Psychotic Disorders", "Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["ego boundary", "stimulus barrier", "delusion", "hallucination", "psychosis", "psychotic", "schizophrenia", "thought disorder"],
        "anchors": ["psychosis", "psychotic", "schizophrenia", "delusion", "hallucination"],
    },
    {
        "id": "medication-transference",
        "core": "The pill is never only a molecule. It can be a feed, a poison, a parental demand, or a humiliating proof of need. Nonadherence is often a transference communication you will miss if you only increase psychoeducation. Ask what it would mean to let this particular doctor put something inside them. That question belongs in the pharmacotherapy visit, not only in the twice-weekly hour.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Somatic Tx & Psychopharmacology", "Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy", "somatic_tx"],
        "keywords": ["meaning of medication", "adherence", "refuses the pill", "transference to medication"],
    },
    {
        "id": "supportive-ego",
        "core": "Supportive psychotherapy is not unstructured kindness. It is a deliberate choice to strengthen existing defenses and reality testing when uncovering would flood a thin ego. The sophistication is in knowing when not to interpret, and in noticing your own contempt for 'just supportive' work. Patients with psychosis, acute trauma, or fragile identity often need this as the treatment, not as a waiting room for the real one.",
        "psychotherapy": ["supportive", "psychodynamic"],
        "diagnoses": ["schizophrenia", "personality-disorder"],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["supportive", "ego function", "strengthen defenses", "reality testing"],
    },
    {
        "id": "cbt-contrast",
        "core": "A senior dynamic listener does not dismiss the automatic thought. They ask whose voice it is, what wish it is guarding, and what would happen between you if the thought were not there to manage the hour. CBT can loosen the thought; the dynamic question is why this particular thought is required to keep a relationship intact. Both can be true in the same patient in the same week.",
        "psychotherapy": ["cbt", "psychodynamic"],
        "diagnoses": ["major-depression", "gad", "panic"],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["automatic thought", "cognitive distortion", "cbt", "schema"],
    },
    {
        "id": "dbt-dialectic",
        "core": "The dialectic is not a branding device. It is a technical stance toward ambivalence: both the wish to change and the wish to stay as one is are granted reality. A psychodynamic cousin is refusing to take sides in the internal conflict. When a resident uses DBT skills to shut down a transference storm, ask whether they are containing or evacuating. Skills can be used in the service of resistance too.",
        "psychotherapy": ["dbt"],
        "diagnoses": ["personality-disorder"],
        "topics": ["Personality Disorders", "Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["dbt", "dialectic", "validation", "skills group"],
    },
    {
        "id": "mi-ambivalence",
        "core": "Ambivalence is not a motivational obstacle. It is the treatment. Rolling with resistance means you do not become the superego the patient already has, which is why confrontation so often increases use. A dynamic ear also hears who the substance is standing in for. If you only develop discrepancy with values, you may miss the loyalty to an internal object that would be betrayed by getting well.",
        "psychotherapy": ["motivational"],
        "diagnoses": ["substance-use"],
        "topics": ["Psychotherapy & Psychodynamics", "Substance Use Disorders"],
        "categories": ["psychotherapy"],
        "keywords": ["motivational interviewing", "ambivalence", "roll with resistance"],
    },
    {
        "id": "ipt-roles",
        "core": "IPT's foci — grief, role dispute, role transition, interpersonal deficits — are a disciplined way of staying with object loss without calling it that. The sophistication is in not letting the treatment drift into a general life-coaching hour. When the 'role transition' is becoming a parent or a widow, you are already on the edge of unfinished mourning. Name the lost role as well as the new one.",
        "psychotherapy": ["ipt"],
        "diagnoses": ["major-depression", "grief"],
        "topics": ["Psychotherapy & Psychodynamics", "Mood Disorders"],
        "categories": ["psychotherapy"],
        "keywords": ["interpersonal therapy", "role transition", "role dispute", "ipt"],
    },
    {
        "id": "yalom-group",
        "core": "The group is the agent, which means your narcissism will be regularly disappointed. Universality and interpersonal learning happen in the here-and-now among members, not in your closing summary. The dynamic task is to track the roles being assigned — scapegoat, favorite, silent witness — including the one assigned to you. If you work only one-to-one inside the circle, you have dissolved the group.",
        "psychotherapy": ["group"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["group therapy", "yalom", "universality", "cohesion", "here and now"],
    },
    {
        "id": "family-triangle",
        "core": "A triangle is a stabilizer, not a mistake. The identified patient is often the one who agreed to carry the affect the couple cannot hold. Detriangling is less about insight than about refusing the invitation to become the third who makes the dyad feel sane. In a consult, notice how quickly the team recruits you into the same triangle the family already uses.",
        "psychotherapy": ["family"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics", "Child & Adolescent Psychiatry"],
        "categories": ["psychotherapy"],
        "keywords": ["family therapy", "detriangle", "identified patient", "triangulation"],
        "anchors": ["family therapy", "identified patient", "triangulation"],
    },
    {
        "id": "acting-out",
        "core": "Acting out puts an unremembered conflict into behavior so that it will not have to become a thought. The technical response is not a limit for its own sake but a translation: what could not be said was done. If you only contain the behavior you get safety without representation. If you only interpret and cannot hold the limit, you get words that the action then disproves.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["personality-disorder", "conduct"],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["acting out", "into behavior", "instead of words"],
    },
    {
        "id": "superego-lacunae",
        "core": "Superego lacunae are not global absence of conscience. They are sanctioned gaps, often unconsciously licensed by a parent, in which a particular transgression does not register as transgression. That is why moralizing fails and why the patient can be scrupulous in one domain and blank in another. The work is to find whose permission is still operating, including yours if you quietly enjoy the outlaw.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["conduct", "personality-disorder"],
        "topics": ["Personality Disorders", "Child & Adolescent Psychiatry", "Forensic Psychiatry & Ethics"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["superego lacunae", "conscience", "acting out", "antisocial", "malingering"],
        "anchors": ["superego lacunae", "malingering", "antisocial"],
    },
    {
        "id": "identification-aggressor",
        "core": "Identification with the aggressor is a solution to terror, not a preference for cruelty. The child becomes what frightened them so that helplessness will not have to be felt again. In adult treatments it shows up as a sudden hardness, a preemptive strike, or a resident who identifies with a sadistic attending. Interpreting it as 'they like power' misses the original panic it is designed to end.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["conduct", "ptsd"],
        "topics": ["Child & Adolescent Psychiatry", "Anxiety, OCD & Trauma/PTSD"],
        "categories": ["psychotherapy", "development"],
        "keywords": ["identification with the aggressor", "becomes the bully", "abused then abusive"],
    },
    {
        "id": "bowlby-attachment",
        "core": "Attachment is a primary system, which means proximity-seeking under threat is not a regression to be interpreted away. In the adult hour, lateness, extra contact, and the last-minute revelation are often attachment behaviors aimed at you. The question is whether you can be used as a secure base from which to explore, or only as a figure who must be monitored. Misreading this as 'borderline neediness' is how treatments become power struggles.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Development & Lifespan", "Child & Adolescent Psychiatry", "Psychotherapy & Psychodynamics"],
        "categories": ["development", "psychotherapy"],
        "keywords": ["attachment", "proximity", "secure base", "bowlby"],
    },
    {
        "id": "mahler-rapprochement",
        "core": "Rapprochement is the toddler's rediscovery of need after a burst of autonomy, and it is noisy on purpose. Shadowing, darting, and ambivalence are the point, not a failure of individuation. Adult patients reenter this when a treatment starts to matter: they come closer and then spoil it. If you experience that as resistance to getting well, you may be repeating the original misreading of need as clinginess.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Development & Lifespan", "Child & Adolescent Psychiatry"],
        "categories": ["development"],
        "keywords": ["rapprochement", "separation individuation", "mahler", "shadowing"],
    },
    {
        "id": "erikson-identity",
        "core": "Identity versus role confusion is not a teenage branding exercise. It is the psychosocial task of assembling identifications into something that can survive intimacy and work. Premature foreclosure — the inherited career, the unexamined orientation, the institutional self of residency — can look like health. In a senior resident, the interesting question is which identifications are still being worn as a false self.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Development & Lifespan", "Child & Adolescent Psychiatry"],
        "categories": ["development"],
        "keywords": ["erikson", "role confusion", "psychosocial stage", "identity versus"],
        "anchors": ["erikson", "role confusion"],
    },
    {
        "id": "oedipal",
        "core": "The oedipal situation is a triangular one: desire, rivalry, and the problem of a third who cannot be eliminated. It is not a cartoon about wanting the opposite-sex parent. In the treatment it appears as competition with your other patients, curiosity about your partner, or a wish to be the exception to the frame. If you interpret only the dyad, you will miss the excluded third who organizes the jealousy.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Development & Lifespan", "Psychotherapy & Psychodynamics"],
        "categories": ["development", "psychotherapy"],
        "keywords": ["oedipal", "oedipus", "phallic", "castration", "rival"],
    },
    {
        "id": "repetition-compulsion",
        "core": "The compulsion to repeat is more conservative than the pleasure principle. The patient does not remember; they stage, often with you as the new edition of the old object. Insight that stays historical leaves the repetition free to continue in the present tense. The leverage is in describing the staging while it is happening, including your own pull to play the assigned part.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["ptsd", "personality-disorder"],
        "topics": ["Psychotherapy & Psychodynamics", "Anxiety, OCD & Trauma/PTSD"],
        "categories": ["psychotherapy"],
        "keywords": ["repetition compulsion", "reenacts", "compulsion to repeat"],
        "anchors": ["repetition compulsion", "reenacts"],
    },
    {
        "id": "id-ego-superego",
        "core": "A structural formulation is a map of a conflict, not a personality type. Ask which agency is speaking, which is under attack, and which you have been invited to join. Residents often side automatically with ego against symptom, which is a moral stance disguised as technique. The more interesting hour is the one in which you can hear the id's claim without becoming it, and the superego's fear without enforcing it.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["id", "ego", "superego", "structural model"],
    },
    {
        "id": "dream-royal-road",
        "core": "The dream is still useful, but not as a crossword of symbols. Listen for the day's residue that chose this dreamer, and for the wish that required disguise. More important is how the patient tells it to you — dumped, withheld, performed, forgotten on the threshold. The telling is a transference event, and often more accessible than the latent content.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["dream", "latent content", "manifest content", "royal road"],
    },
    {
        "id": "consultation-meaning",
        "core": "On a consult service the dynamic question is what this symptom is doing in this relationship, on this ward, today. Secondary gain, splitting of the team, and the evacuation of affect into psychiatry are the usual offerings. Your job is not to be cleverer than medicine. It is to metabolize what the system cannot think, and to hand back a formulation the team can use without humiliation.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["somatic-symptom", "delirium"],
        "topics": ["Consultation-Liaison / Psychosomatic Medicine"],
        "categories": ["consultation", "psychotherapy"],
        "keywords": ["consult", "consultation", "ward", "sick role", "secondary gain"],
        "fallback_for": ["consultation"],
    },
    {
        "id": "secondary-gain",
        "core": "Primary gain is the internal relief; secondary gain is the interpersonal payoff. Both can be true, and moralizing about the second one is how consults become adversarial. The more precise question is which relationship would have to change if the symptom remitted. That is often more frightening to the system than to the patient.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["somatic-symptom", "factitious"],
        "topics": ["Dissociative, Somatic Symptom & Eating Disorders", "Consultation-Liaison / Psychosomatic Medicine"],
        "categories": ["consultation", "psychotherapy"],
        "keywords": ["secondary gain", "primary gain", "sick role"],
    },
    {
        "id": "interview-defense",
        "fallback_for": ["diagnostics", "psychotherapy"],
        "core": "In the interview, the next sentence after a feeling appears is often the defense arriving to restore equilibrium. Do not only collect the content that follows. Mark the sequence: affect, then joke, then a question about your weekend. That sequence will be the treatment, repeated at higher resolution, if you ever get one.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Interviewing & Assessment"],
        "categories": ["diagnostics", "psychotherapy"],
        "keywords": ["when the feeling appeared", "changed the subject", "interview defense"],
    },
    {
        "id": "adhd-self-esteem",
        "core": "Chronic correction produces a child identified as the problem, and later an adult who pre-emptively shames themselves so you will not have to. Stimulant response does not dissolve that identification. In the hour, notice whether they offer you their worst self first. That offering is a transference gift and a test: will you become another person who already knows they are too much?",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["adhd"],
        "topics": ["Child & Adolescent Psychiatry"],
        "categories": ["development", "psychotherapy"],
        "keywords": ["shame", "the problem child", "always in trouble", "adhd"],
    },
    {
        "id": "autism-object",
        "core": "Early analytic theories of autism as a withdrawn object choice did not survive the evidence, and they harmed families. The remaining psychodynamic contribution is more modest and more honest: helping parents mourn the child they imagined without pathologizing the child they have. Your countertransference of helplessness is data about that mourning, not a warrant to invent a refrigerator mother.",
        "psychotherapy": ["psychodynamic", "family"],
        "diagnoses": ["autism"],
        "topics": [],
        "categories": ["development"],
        "keywords": ["autism", "autistic", "asd", "mourn the imagined child"],
    },
    {
        "id": "neuro-deficit-meaning",
        "core": "A lesion still has a meaning in the room: how the patient grieves a lost function, and how the family now speaks for a mind that used to speak for itself. Do not interpret neurologic signs as conversion, and do not treat the grief as a sideshow. The dynamic work is around narcissistic injury, dependency, and who is allowed to know what has been lost. Families often need help mourning while the patient is still in the chair.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["dementia"],
        "topics": ["Neurocognitive Disorders (Dementia/Delirium)"],
        "categories": ["psychotherapy"],
        "keywords": ["loss of function", "grief the illness", "who speaks for", "aphasia", "dementia", "stroke", "lesion", "hemiparesis", "parkinson", "huntington", "multiple sclerosis", "seizure", "myelopathy", "lewy", "neurocognitive"],
        "fallback_for": ["neurology"],
    },
    {
        "id": "pharmacology-meaning",
        "core": "A receptor story and a transference story can both be true in the same prescription. Dopamine blockade does not cancel the meaning of being 'put on something' by a powerful other. If the patient improves and then stops the drug, ask whether health itself has become a submission. The sophisticated prescriber listens for that even while checking the QTc.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": [],
        "categories": ["psychotherapy"],
        "keywords": ["put on a med", "powerful doctor", "prescribe", "lithium", "clozapine", "antipsychotic", "antidepressant", "ssri", "stimulant"],
        "fallback_for": ["somatic_tx"],
    },
    {
        "id": "forensic-superego",
        "core": "Knowing right from wrong is not the same as having a superego that can generate guilt and guide action under pressure. Forensic questions about capacity sit next to this, but they are not identical. A patient can recite the statute and still be organized by a lacuna, a psychotic identification, or a loyalty to an internal object that outranks the law. Your report should not pretend a cognitive test has measured that.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Forensic Psychiatry & Ethics"],
        "categories": ["practice_issues", "psychotherapy"],
        "keywords": ["right from wrong", "conscience", "insanity", "superego", "capacity", "competency", "advance directive", "tarasoff", "duty to warn"],
        "fallback_for": ["practice_issues"],
    },
    {
        "id": "sleep-dream-guard",
        "core": "Insomnia is sometimes a refusal to dream, which is a refusal to meet the day's unfinished business without a witness. Nightmares can be failed dreams, repetitions that never quite become representations. Before you add a hypnotic, ask what the sleeplessness is standing guard against. The answer is often a feeling that would arrive if the watch were stood down.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["insomnia", "narcolepsy", "parasomnia"],
        "topics": ["Sleep-Wake Disorders"],
        "categories": ["psychotherapy"],
        "keywords": ["nightmare", "dream wish", "insomnia", "refusal to sleep"],
        "anchors": ["insomnia", "nightmare", "dream"],
    },
    {
        "id": "postpartum-object",
        "core": "The baby is a beloved other and a mirror of an old deprivation at once. Postpartum collapse often reactivates the new mother's experience of being mothered, including identifications she did not know she had. The infant's need is real and so is the ghost in the nursery. Treating only the DSM episode can miss the object that just entered the house.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["major-depression"],
        "topics": ["Mood Disorders", "Consultation-Liaison / Psychosomatic Medicine"],
        "categories": ["psychotherapy", "consultation"],
        "keywords": ["postpartum", "new mother", "being mothered", "perinatal"],
    },
    {
        "id": "working-alliance",
        "core": "The working alliance is the non-neurotic collaboration that makes transference interpretable rather than merely lived. You cannot interpret from a collapsing alliance, and you cannot build an alliance by being endlessly gratifying. In more disturbed patients the alliance is intermittent and has to be reconstructed after every rupture. Calling that 'resistance' is how you miss the repair.",
        "psychotherapy": ["psychodynamic", "supportive"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["working alliance", "therapeutic alliance", "rapport"],
    },
    {
        "id": "devaluation",
        "core": "Devaluation protects against envy and against the pain of needing someone who can disappoint you. Yesterday's perfect doctor becomes today's idiot after one missed call because the alternative is to feel small. If you defend your competence, you have accepted the polarity. The more useful comment is about the switch, and about what it would cost to keep you as a mixed object.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["personality-disorder"],
        "topics": ["Personality Disorders"],
        "categories": ["psychotherapy"],
        "keywords": ["devalu", "worthless", "you don't care"],
    },
    {
        "id": "idealization",
        "core": "Idealization may be a developmental need for a selfobject, or a primitive defense that will flip the moment you fail. The clinical test is whether the shine can survive an ordinary disappointment. If you enjoy being idealized, you will delay that test. If you puncture it too early to stay modest, you may inflict a fragmenting injury you then misread as entitlement.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["personality-disorder"],
        "topics": ["Personality Disorders"],
        "categories": ["psychotherapy"],
        "keywords": ["idealiz", "puts on a pedestal", "you are the only one"],
    },
    {
        "id": "free-association",
        "core": "Free association is a method, not a personality style. The fundamental rule asks the patient to suspend the usual censorship, which means the first interesting data are the places they cannot. Silence, a sudden joke, a question about your notes — those are associations too. If you fill every pause, you have become the censor.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["free association", "whatever comes to mind", "fundamental rule"],
    },
    {
        "id": "vaillant-mature",
        "core": "Mature defenses are not morally better so much as more flexible: they keep more of the wish and more of the relationship. Sublimation, suppression, humor, and altruism can all be used masochistically. The technical question is whether the defense includes the self or erases it. Do not interpret away a mature defense that is working; you will be experienced as envious of the patient's adaptation.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["sublimation", "altruism", "suppression", "mature defense", "vaillant"],
        "anchors": ["sublimation", "vaillant", "mature defense"],
    },
    {
        "id": "projection",
        "core": "Projection locates an unacceptable inner impulse in someone else, and in paranoid organizations it is a life-support system, not a cognitive error. Direct contradiction ('I am not attacking you') confirms the projection by making you the denier. Better to explore what it would cost to find the impulse inside. Safety comes first if reality testing is gone; curiosity comes first if it is not.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["personality-disorder"],
        "topics": ["Psychotherapy & Psychodynamics", "Personality Disorders"],
        "categories": ["psychotherapy", "psychopathology"],
        "keywords": ["projection", "paranoid", "it's them", "accuses others"],
    },
    {
        "id": "brief-dynamic",
        "core": "A brief dynamic treatment lives or dies by the focal conflict you choose and your willingness to keep returning to it. The temptation is to follow every associative trail and end with a well-liked hour that changed nothing. Time-limit is itself an interpretation of the oedipal and attachment meanings of ending. If you cannot bear the limit, the patient will not be able to use it.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": ["major-depression"],
        "topics": ["Psychotherapy & Psychodynamics"],
        "categories": ["psychotherapy"],
        "keywords": ["brief dynamic", "focal conflict", "time-limited", "malan"],
    },
    {
        "id": "brain-map",
        "fallback_for": ["neuro_sci"],
        "core": "The map is not the territory. A tract, a nucleus, or a working-memory circuit can be exactly right on this item and still leave you with a person who will later sit down and tell you what that circuit feels like from the inside. Do not let the elegance of localization become a defense against the mess of a life. Know the anatomy cold, then leave room for meaning when the patient arrives.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Neuroanatomy & Neuroscience"],
        "categories": ["neuro_sci"],
        "keywords": ["cortex", "tract", "nucleus", "receptor", "circuit"],
    },
    {
        "id": "numbers-not-person",
        "fallback_for": ["research_stats", "epidemiology"],
        "core": "A ratio is a claim about a population, not a verdict on the person in front of you. Residents sometimes treat a relative risk or a p-value as if it had settled the case, which is a manic defense against uncertainty. Know the number, then ask what it cannot tell you about this patient's objects, motives, and fear. The dynamic contribution is not to sneer at the statistic; it is to keep it from becoming the whole story.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Epidemiology, Biostatistics & Human Development"],
        "categories": ["research_stats", "epidemiology"],
        "keywords": ["relative risk", "p-value", "odds ratio", "prevalence", "incidence"],
    },
    {
        "id": "contingency-object",
        "fallback_for": ["behavioral_sci"],
        "core": "Reinforcement, modeling, and extinction are real. So is the object who is doing the reinforcing. A contingency that stops a parent's criticism also organizes a child around an internal critic you will meet later in the transference. Learn the schedule, then ask whose voice the contingency is carrying. Behaviorism and object relations are not rival religions here; they are two descriptions of the same shaping.",
        "psychotherapy": ["behavioral", "psychodynamic"],
        "diagnoses": [],
        "topics": ["Behavioral Science & Psychology"],
        "categories": ["behavioral_sci"],
        "keywords": ["reinforcement", "extinction", "conditioning", "operant", "classical"],
    },
    {
        "id": "milestone-mind",
        "fallback_for": ["development"],
        "core": "A developmental milestone is a capacity, not a personality. Object permanence, rapprochement, and identity consolidation are the scaffolding on which later transference will be built. If you only memorize the age and miss what the child can now hold in mind, you will be surprised when the adult cannot. The dynamic question is which later relationship still requires a capacity that never quite arrived.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": ["Development & Lifespan", "Child & Adolescent Psychiatry"],
        "categories": ["development"],
        "keywords": ["milestone", "object permanence", "piaget", "developmental stage"],
    },
    {
        "id": "formulation-second-look",
        "fallback_for": ["psychopathology", "uncategorized", "admin_systems", "clinical_psychiatry", "neurosciences"],
        "core": "A finding or a DSM name is a starting cut, not a formulation. After you have the criteria, the lab, or the imaging, the dynamic question is still which wish, which fear, and which object relation this picture is organized around. Two patients can share this item and need opposite technical moves. The sophistication is in knowing when that second look would change what you do next, and when it would only decorate a finding you already have.",
        "psychotherapy": ["psychodynamic"],
        "diagnoses": [],
        "topics": [],
        "categories": ["psychopathology"],
        "keywords": ["formulation", "criteria", "differential"],
    },
]
