// A rotating pool of (groan-worthy, on purpose) psychiatry dad jokes for the
// daily reminder email. One per calendar day, shared by everyone that day —
// the pool's length IS the rotation period, so keep it at 90 for a 90-day
// cycle before jokes repeat. Add more entries to lengthen the cycle.
export const JOKES: string[] = [
  "Why did the neurotransmitter break up with the receptor? It just wasn't binding anymore.",
  "What do you call a psychiatrist who's always calm? A Xanax-ident.",
  "Why don't psychiatrists ever get lost? They always find their patients' locus of control.",
  "What's a psychiatrist's favorite genre of music? Anything with good serotonin uptake.",
  "Why did the SSRI bring a jacket? In case of a chemical imbalance in the weather.",
  "What do you call a benzo that tells jokes? A Xani-comedian.",
  "Why was the lithium always so level-headed? Great mood stability.",
  "What did the therapist say to the broken pencil? \"No point dwelling on it.\"",
  "Why did the antipsychotic go to therapy? It had some negative symptoms to work through.",
  "What's a psychiatrist's favorite exercise? Free association.",
  "Why did the resident bring a ladder to rounds? To reach the higher levels of care.",
  "What do you call an anxious pigeon? A worry-wort.",
  "Why did the dopamine cross the synapse? To get to the other receptor.",
  "What's the most punctual neurotransmitter? Serotonin — always on schedule.",
  "Why did the psychiatrist break up with the calendar? Too many dates with Axis issues.",
  "What do you call a therapist who works with clocks? A time-management specialist.",
  "Why did the MAOI refuse the cheese plate? Tyramine drama.",
  "What's an antidepressant's favorite dance? The SSRI shuffle.",
  "Why did the patient bring string to therapy? To work through their attachment issues.",
  "What do you call a psychiatrist who loves gardening? A mood cultivator.",
  "Why did the amygdala go to the party? It heard there'd be a fight-or-flight risk.",
  "What's a psychiatrist's favorite board game? Sorry! — great for processing guilt.",
  "Why did the stimulant show up early? Excellent follow-through.",
  "What do you call two antipsychotics on a date? A dopamine blockbuster.",
  "Why did the mood ring break up with the patient? Too many mixed episodes.",
  "What's a resident's favorite coffee order? Anything with good compliance.",
  "Why did the hippocampus write everything down? Bad short-term memory for appointments.",
  "What do you call a psychiatrist who tells dad jokes? Board-certified in punny disorders.",
  "Why did the anxious neuron skip the party? Social phobia of crowded synapses.",
  "What's the difference between a psychiatrist and a magician? One pulls rabbits, the other pulls insight.",
  "Why did the benzodiazepine retire early? Tolerance issues.",
  "What do you call a mood stabilizer who tells jokes? Steady humor.",
  "Why did the psychiatrist bring a pillow to work? For all the sleep-hygiene talks.",
  "What's a therapist's favorite baking tool? A validating whisk.",
  "Why did the SSRI apply for a new job? It wanted more receptor engagement.",
  "What do you call a nervous system that overreacts? Dramatic — very dramatic.",
  "Why did the antipsychotic join the choir? Great at blocking out negative notes.",
  "What's a psychiatrist's favorite fruit? The applecation of DSM criteria.",
  "Why did the resident fall asleep during grand rounds? REM rebound from call.",
  "What do you call an over-caffeinated psychiatrist? A differential-diagnosis machine.",
  "Why did the placebo file a complaint? It felt like nothing was happening.",
  "What's a psychiatrist's least favorite kind of significance? Statistical, without being clinical.",
  "Why did the ECT machine get promoted? Great at resetting expectations.",
  "What do you call a psychiatrist who loves the beach? A wavelength specialist.",
  "Why did the patient with ADHD bring a timer everywhere? Time-blindness prevention.",
  "What's the most forgetful part of the brain? The hippo-can't-remember-us.",
  "Why did the ketamine clinic open a bakery? For the rapid rise.",
  "What do you call a psychiatrist who juggles? Great at managing comorbidities.",
  "Why did the ego go to couples therapy? Constant conflict with the id.",
  "What's a psychiatrist's favorite kind of joke? One with good insight.",
  "Why did the tricyclic get benched? Too many side effects, not enough support.",
  "What's the tidiest kind of chart? One from a very well-organized episode.",
  "Why did the psychiatrist bring a flashlight to session? To help patients find insight in the dark.",
  "What's a therapist's favorite kind of humor? Dry — very dry.",
  "Why did the neuron get promoted? Great at firing on all cylinders.",
  "What do you call an antidepressant with a great sense of humor? Well-adjusted.",
  "Why did the patient bring a map to therapy? To navigate their family of origin.",
  "What's a psychiatrist's favorite kind of pasta? Neuro-noodles — they go straight to the point.",
  "Why did the sleep specialist quit? Tired of the same old dreams.",
  "What do you call two psychiatrists arguing over a diagnosis? A differential.",
  "Why did the panic attack apply for a job? Excellent at rapid onset.",
  "What's a psychiatrist's favorite plant? The mood-ring succulent — always changing color.",
  "Why did the resident love working nights? Great exposure therapy for sleep deprivation.",
  "What do you call a psychiatrist who studies dreams? A REM-arkable listener.",
  "Why did the antipsychotic get a promotion? Excellent at managing the negative symptoms of a bad meeting.",
  "What's a psychiatrist's favorite kind of weather? Partly manic, with a chance of depression.",
  "Why did the therapist bring an umbrella? In case of an emotional downpour.",
  "What do you call a psychiatrist who loves puzzles? Great at piecing together a differential.",
  "Why did the mood chart look like a rollercoaster? Bipolar disorder, type \"thrill ride.\"",
  "What's a psychiatrist's favorite music quality? Good rhythm — circadian rhythm, that is.",
  "Why did the SNRI get invited to two parties? Dual mechanism of action.",
  "What do you call an antidepressant that tells bad jokes? SSR-eye-roll.",
  "Why did the resident bring snacks to call? Cortisol management.",
  "What's a psychiatrist's favorite kind of exercise class? Cognitive reframing.",
  "Why did the patient bring a thesaurus to therapy? To reframe the negative self-talk.",
  "What do you call two neurons who can't agree? A synaptic standoff.",
  "Why did the psychiatrist love crossword puzzles? Great practice for differential diagnosis.",
  "What's a psychiatrist's favorite tea? Chamomile — great for that GABA boost.",
  "Why did the antipsychotic apply to be a bouncer? Great at blocking unwanted activity.",
  "What do you call a psychiatrist who loves baking bread? Great at helping things rise slowly, with patience.",
  "Why did the resident bring a stopwatch to the ED? To track time to stabilization.",
  "What's a psychiatrist's favorite kind of story? One with a good arc — and insight by the end.",
  "Why did the mood stabilizer get a raise? Consistently reliable performance reviews.",
  "What do you call a very calm limbic system? Well-regulated — the dream.",
  "Why did the psychiatrist bring a compass to work? To help patients find direction.",
  "What's a psychiatrist's favorite kind of workout? Reps — of good habits, that is.",
  "Why did the antidepressant show up to the interview early? Great onset of action.",
  "What do you call a psychiatrist who loves stargazing? Always looking for patterns in constellations of symptoms.",
  "Why did the resident love night float? Great chance to practice sleep hygiene — for everyone else.",
  "What's a psychiatrist's favorite way to end a joke? With a good follow-up.",
];

/** Deterministic pick — the same joke for everyone on a given calendar day,
    cycling through the full pool before repeating. */
export function jokeForToday(): string {
  const daysSinceEpoch = Math.floor(Date.now() / 86_400_000);
  return JOKES[daysSinceEpoch % JOKES.length];
}
