"""Quantitative psychotherapy evidence used only on matching Therapy decks."""

FACTS = [
    {
        "id": "therapy-psychodynamic-ltpp",
        "modalities": ["Psychodynamic"],
        "anchors": ["psychodynamic psychotherapy", "long-term", "long term", "ltpp", "effect size", "efficacy", "effectiveness", "outcome", "evidence", "meta-analysis", "common factor", "wampold"],
        "sentence": "A 23-study meta-analysis of long-term psychodynamic psychotherapy reported a between-group effect size of 1.8; treated patients averaged better outcomes than 96 percent of comparison patients.",
        "source_label": "JAMA, 2008",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/18827212/",
        "source_year": 2008,
    },
    {
        "id": "therapy-alliance-outcome",
        "modalities": ["Psychodynamic"],
        "anchors": ["alliance", "working relationship", "therapeutic relationship", "bond component", "bordin"],
        "sentence": "A meta-analysis of 295 studies and more than 30,000 patients found that the therapeutic alliance correlated with psychotherapy outcome at r 0.278 across treatment approaches.",
        "source_label": "Psychotherapy, 2018",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/29792475/",
        "source_year": 2018,
    },
    {
        "id": "therapy-rupture-repair",
        "modalities": ["Psychodynamic"],
        "anchors": ["rupture", "safran", "muran"],
        "sentence": "Across 11 studies and 1,314 patients, successful therapeutic-alliance rupture repair had a moderate association with better outcome, r 0.29 and d 0.62.",
        "source_label": "Psychotherapy, 2018",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/30335462/",
        "source_year": 2018,
    },
    {
        "id": "therapy-psychodynamic-depression",
        "modalities": ["Psychodynamic"],
        "anchors": ["depression", "depressive", "dysthymia"],
        "sentence": "An individual-participant meta-analysis found short-term psychodynamic psychotherapy reduced depressive symptoms versus controls with an effect size of minus 0.62.",
        "source_label": "Clinical Psychology Review, 2023",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/36958077/",
        "source_year": 2023,
    },
    {
        "id": "therapy-psychodynamic-youth",
        "modalities": ["Psychodynamic"],
        "anchors": ["child", "children", "adolescent", "adolescence", "pediatric", "paediatric"],
        "sentence": "Across 11 studies and 655 children and adolescents, short-term psychodynamic psychotherapy had a within-group effect size of Hedges g 1.07, although it did not outperform mostly robust comparison treatments.",
        "source_label": "Journal of the American Academy of Child and Adolescent Psychiatry, 2013",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/23880496/",
        "source_year": 2013,
    },
    {
        "id": "therapy-psychotherapy-bpd",
        "modalities": ["Psychodynamic"],
        "anchors": ["borderline", "bpd"],
        "sentence": "A 75-trial review found psychotherapy reduced borderline personality disorder (BPD) severity versus treatment as usual with a standardized mean difference of minus 0.52; the self-harm effect was minus 0.32.",
        "source_label": "Cochrane Database of Systematic Reviews, 2020",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/32368793/",
        "source_year": 2020,
    },
    {
        "id": "therapy-cbt-four-disorders",
        "modalities": ["CBT"],
        "sentence": "Across 144 acute-treatment trials, CBT effect sizes versus control conditions ranged from Hedges g 0.75 for major depression to 0.88 for social anxiety disorder.",
        "source_label": "World Psychiatry, 2016",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/27717254/",
        "source_year": 2016,
    },
    {
        "id": "therapy-dbt-adolescent",
        "modalities": ["DBT"],
        "sentence": "A meta-analysis of adolescent DBT found small-to-moderate advantages over controls for reducing self-harm, Hedges g minus 0.44, and suicidal ideation, g minus 0.31.",
        "source_label": "Psychological Medicine, 2021",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/33875025/",
        "source_year": 2021,
    },
    {
        "id": "therapy-mi-effect",
        "modalities": ["MI"],
        "sentence": "A motivational interviewing meta-analysis found an average short-term between-group effect size of 0.77, declining to 0.30 at follow-ups extending to one year.",
        "source_label": "British Journal of General Practice, 2005",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/17716083/",
        "source_year": 2005,
    },
    {
        "id": "therapy-act-effect",
        "modalities": ["ACT"],
        "sentence": "An 18-trial meta-analysis found ACT had an overall effect size of 0.42 versus control conditions; it was not significantly better than established treatments.",
        "source_label": "Psychotherapy and Psychosomatics, 2009",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/19142046/",
        "source_year": 2009,
    },
    {
        "id": "therapy-family-relapse",
        "modalities": ["Group, family & couples"],
        "sentence": "A 25-study meta-analysis found that family interventions involving relatives in schizophrenia treatment reduced relapse by about 20 percent, with particularly marked effects when the work lasted longer than three months.",
        "source_label": "Schizophrenia Bulletin, 2001",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/11215551/",
        "source_year": 2001,
    },
    {
        "id": "therapy-ipt-depression",
        "modalities": ["IPT"],
        "sentence": "Across 16 controlled studies of depression, interpersonal psychotherapy had an effect size of 0.63, corresponding to a number needed to treat of 2.91.",
        "source_label": "American Journal of Psychiatry, 2011",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/21362740/",
        "source_year": 2011,
    },
    {
        "id": "therapy-bpd-psychotherapy",
        "modalities": ["Integration"],
        "sentence": "A 75-trial review found psychotherapy reduced borderline personality disorder (BPD) severity versus treatment as usual with a standardized mean difference of minus 0.52; the self-harm effect was minus 0.32.",
        "source_label": "Cochrane Database of Systematic Reviews, 2020",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/32368793/",
        "source_year": 2020,
    },
    {
        "id": "therapy-mbt-self-harm",
        "modalities": ["MBT"],
        "sentence": "A 14-study MBT meta-analysis found a pre-post self-harm effect of Hedges g minus 0.82, but MBT was not superior to control treatments for self-harm in controlled comparisons.",
        "source_label": "eClinicalMedicine, 2024",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/38279664/",
        "source_year": 2024,
    },
    {
        "id": "therapy-tfp-bpd",
        "modalities": ["TFP & Supportive"],
        "anchors": ["tfp", "transference-focused", "transference focused", "kernberg"],
        "sentence": "In a randomized borderline personality disorder trial, transference focused psychotherapy had 38.5 percent dropout versus 67.3 percent with community psychotherapy and a borderline-symptom effect size of 1.6.",
        "source_label": "British Journal of Psychiatry, 2010",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/20435966/",
        "source_year": 2010,
    },
    {
        "id": "therapy-supportive-depression",
        "modalities": ["TFP & Supportive"],
        "anchors": ["supportive", "non-directive", "nondirective"],
        "sentence": "A 48-trial meta-analysis found non-directive supportive therapy for depression had Hedges g 0.53 versus controls; it was modestly less effective than other psychotherapies, g minus 0.21.",
        "source_label": "Journal of Affective Disorders, 2024",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/38211757/",
        "source_year": 2024,
    },
    {
        "id": "therapy-trauma-dropout",
        "modalities": ["Trauma-focused"],
        "sentence": "Across randomized trials of psychological therapies for PTSD, the pooled dropout rate was 16 percent, with trauma focused treatments showing significantly greater dropout.",
        "source_label": "European Journal of Psychotraumatology, 2020",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/32284816/",
        "source_year": 2020,
    },
    {
        "id": "therapy-pe-frequency",
        "modalities": ["Trauma-focused"],
        "sentence": "In a 35-trial prolonged exposure meta-analysis, programs prescribed at least twice weekly had 21 percent dropout versus 34 percent when sessions were less frequent.",
        "source_label": "Journal of Traumatic Stress, 2022",
        "source_url": "https://pubmed.ncbi.nlm.nih.gov/35278229/",
        "source_year": 2022,
    },
]
